### ISSUE TITLE
Openstack: Legacy API calls

### ISSUE THREAD

**Issue by bmshouse** [mistio/mist-ce#1000]
I was hoping to contribute some changes to CE that offer support for different version of OpenStack. In testing our deployment we noticed that [CinderV3](https://docs.openstack.org/api-ref/block-storage/v3/) is not used by default, but it was easily remedied by adding the CinderV2 endpoint. However the Networking is proving to be a bit more contentious, and will likely require some Apache rewrite configuration. Mist.io CE uses the legacy [Nova Networking](https://docs.openstack.org/api-ref/compute/#networks-os-networks-deprecated) which is removed in OpenStack Ussuri. The supported [Neutron Networking](http://developer.openstack.org/api-ref-networking-v2.html) does not appear to be enabled by default. In most cases, the changes are simple modification of the API URL and the correct API version can be deduced from the endpoint URL.

Can you point me to where I would contribute such adaptions?  

Thank you!

**Comment by bmshouse** [comment]
While the GitHub search did not turn this up, it looks like the calls are coming from libcloud. Would you prefer I contribute to the upstream project directly?

**Comment by d-mo** [comment]
Hi @bmshouse 
If all the changes you need to make are on the Libcloud side, then it's probably better to contribute them to the upstream project. We'll pick them up once they're merged.
Thanks!

**Comment by bmshouse** [comment]
@d-mo Thank you!
