### ISSUE TITLE
can not support AWS HongKong

### ISSUE THREAD

**Issue by alanxie1986** [mistio/mist-ce#1003]
can you fix support aws HongKong? and support tencent cloud?

**Comment by cpsaltis** [comment]
v4.4.1 was just released and adds support for Hong Kong, Milan, Bahrain and Cape Town AWS regions. Please keep in mind you have to opt in those from the AWS console.

We don't plan to support Tencent cloud in the near term. I'll get back to you if anything changes.

**Comment by alanxie1986** [comment]
thanks
