### ISSUE TITLE
Docker startup ERROR: for mist_nginx_1  a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by AdrianChallinorOsiris** [mistio/mist-ce#1004]
Following instructions for installing community edition. 

The system errors when trying to load mist_nginx_1 
Command used was: **sudo docker-compose up -d**

Error log attached
[x.txt](https://github.com/mistio/mist-ce/files/6156889/x.txt)

**Comment by d-mo** [comment]
The answer is in the attached log:
```
0.0.0.0:80: bind: address already in use
```
The nginx container fails to start because some other program is listening on port 80.
