### ISSUE TITLE
Package for ububtu or redhat

### ISSUE THREAD

**Issue by xaoc7** [mistio/mist-ce#1007]
It would be nice if you can provide packages for some well known Linux distribution like Ubuntu or RedHat. Probably there are other people and companies that have no willing or time to spend learning and integrating Docker in their existing environment.

**Comment by xaoc7** [comment]
Any plans for handling above request?

**Comment by xaoc7** [comment]
Ok thanks amilion for answering my questions! Good luck with that project.

**Comment by cpsaltis** [comment]
I'm terribly sorry @xaoc7, I somehow missed the notifications from your messages.

Unfortunately we can't provide packages for Linux distros without Docker. Docker compose and kubernetes (for the more HA setup) are integral to the application's architecture and can't be omitted.
