### ISSUE TITLE
Huawei Cloud Support

### ISSUE THREAD

**Issue by 775838893** [mistio/mist-ce#1012]
Possible add Huawei Cloud support? It‘s as same as Alibaba Cloud

**Comment by cpsaltis** [comment]
Hi @775838893,
 
Huawei Cloud support is not part of our short term plans. Adding new clouds is not very simple and increases the maintenance effort. For this reason, we are very cautious with new integrations.

Having said that, we'd be happy to assist you if you'd like to do it yourself. Would this be an option?

**Comment by 775838893** [comment]
Thank you for your reply. I'm sorry I can't contribute to the project because of my insufficient level. Ha ha

**Comment by cpsaltis** [comment]
Is this really blocking you @775838893? I'd love to learn more about your use case as we're planning future releases. You can reach me directly at cpsaltis at mist.io.
