### ISSUE TITLE
Vultr missing attributes

### ISSUE THREAD

**Issue by kp3nguinz** [mistio/mist-ce#1015]
I noticed that Vultr buckets, networks, and volumes seem to be missing. Any plans to add?
Love the project, and if need be I may be able to throw some dev hours to support in Jan/ Feb.

**Comment by cpsaltis** [comment]
We don't have short term plans to add these @kp3nguinz. We'd me more than happy to accept your contributions. We can also set up a call to guide you. Let me know when ready.
