### ISSUE TITLE
Setting up SSL and Certs

### ISSUE THREAD

**Issue by mmmccain** [mistio/mist-ce#1017]
I am missing something basic, but I hope the answer will help others. How do I setup SSL for mist.io. I can not use certbot as port 80 is occupied with mist and I can not reach the document root, as it is running in docker. Assistance is very welcome.

**Comment by cpsaltis** [comment]
Hi @mmmccain,

If you are deploying Mist with Docker Compose the relevant docs are [here](https://github.com/mistio/mist-ce#tls-settings).

If you are deploying to a Kubernetes cluster with Heml, check out [here](https://github.com/mistio/mist-ce#tls-configuration).

I hope these help.

**Comment by mmmccain** [comment]
That did not go well. Now I have broken mist.  I should not have followed those steps without having certs in place. 
Certbot needs access to port 80 or the webroot to create the certs. Neither are available. Port 80 is used by mist.io and document root is in the docker container.

**Comment by d-mo** [comment]
1. Shut down Mist: `docker-compose down`
2. Create the cert using certbot
3. Configure Mist to use the cert as described in the docs
4. Bring everything back up: `docker-compose up -d`

**Comment by mmmccain** [comment]
Yeap.... thank you!
