### ISSUE TITLE
Shell and monitoring not working after SSL

### ISSUE THREAD

**Issue by mmmccain** [mistio/mist-ce#1018]
I have mist going and with SSL. Prior to SSL, shell was working. Now that SSL is enabled, it is not and neither is monitoring. I presuming it is related to the URI. Do I need to change it to the FQDN and https? 

Thank you

**Comment by mmmccain** [comment]
Ok... This one was easy. You need to set the CORE_URI = "http://198.51.100.12" to the FQDN and https after enabling SSL. Both are working like a charm.

**Comment by mmmccain** [comment]
BTW: After you change the CORE URI, you need to bring mist down and back up, associate each server, disable monitoring and then reenable it.

**Comment by cpsaltis** [comment]
Glad to see everything worked out for you @mmmccain. Just out of curiosity, how do you plan to use Mist?

**Comment by mmmccain** [comment]
The short answer, I am a big fan of MAAS, at least in the datacenter. MAAS is way too heavy to manage just a few servers and it really does not do ansible out of the box. I am hoping mist is going to allow me to manage a small LXD cloud, enabling me to move each workload into a machine container and then into a LXD Cluster. 

Mist will also let me play and learn without increasing my costs. I current lease 10 cloud nodes of one type or another. I will reduce this to 3 through containers and increase performance. I can do this without of mist, but to be host, mist has been an inspiration for me to rebuild in this way. I do not need k8s or even docker. I have 10 workloads. Mist, an LXD cluster and some ansible scripts and I have a functional portable cloud. 

Major kudos for this project. This should be rocking it in the enterprise space! Right now I am trying to break it the best I can. I deployed over 500K nodes of openstack in my professional life (now retired). I wonder how many of those cores I could have saved with mist? 

So, now I am relearning ansible, again and enjoying the well thought out pane of glass that represents my 10 humble nodes.

**Comment by cpsaltis** [comment]
Wow! Thanks a lot for the feedback!

I'd love to learn a bit more from your experience. Reach out to me directly at cpsaltis at mist.io if you have 20mins to discuss in the coming days.
