### ISSUE TITLE
RDS & ELB for aws

### ISSUE THREAD

**Issue by eslam-gomaa** [mistio/mist-ce#1034]
Hi,

Any plans for adding more AWS services support specifically RDS & ELB ?

**Comment by cpsaltis** [comment]
We don't have immediate plans for these @eslam-gomaa but eventually we would like to support them.

I would love to learn a bit more about your use case. Are these missing features blocking you? 

We could also discuss directly if you like at cpsaltis at mist.io.

**Comment by eslam-gomaa** [comment]
Hi chris,  we use many aws services and and we're actually need a full insight of the big main services (the ones that affect the price)

**Comment by eslam-gomaa** [comment]
sorry for late reply @cpsaltis,

the main ones are RDS, ELB, EKS, Opensearch, Glue and Lambda

**Comment by cpsaltis** [comment]
EKS is coming in a couple of weeks @eslam-gomaa but I'm afraid we don't have immediate plans for the rest.

**Comment by eslam-gomaa** [comment]
sure, I understand that it will take time 👍 

will close the issue then
