### ISSUE TITLE
Vsphere Integration Does Not Work

### ISSUE THREAD

**Issue by fia5000** [mistio/mist-ce#691]
`
2016-02-17 22:04:12,668 ERROR uWSGIWorker3Core0 methods - add_cloud_v_2: Error while trying list_nodes: AttributeError("'VSphereNodeDriver' object has no attribute 'connection'",)
2016-02-17 22:04:12,668 INFO uWSGIWorker3Core0 views - exception_handler_mist: MistError: CloudUnavailableError('Cloud unavailable',)
[pid: 245|app: 0|req: 15/55] 127.0.0.1 () {52 vars in 843 bytes} [Wed Feb 17 22:04:12 2016] POST /clouds => generated 17 bytes in 15 msecs (HTTP/1.1 503) 2 headers in 96 bytes (1 switches on core 0)
2016-02-17 22:04:49,372 INFO uWSGIWorker1Core0 methods - add_cloud_v_2: Adding new cloud in provider 'vsphere' with Api-Version: 2
2016-02-17 22:04:49,375 INFO uWSGIWorker1Core0 connectionpool - _new_conn: Starting new HTTPS connection (1): 192.168.2.247
/home/mist/mist.io/eggs/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
2016-02-17 22:04:49,384 ERROR uWSGIWorker1Core0 methods - add_cloud_v_2: Error while trying list_nodes: AttributeError("'VSphereNodeDriver' object has no attribute 'connection'",)
2016-02-17 22:04:49,385 INFO uWSGIWorker1Core0 views - exception_handler_mist: MistError: CloudUnavailableError('Cloud unavailable',)
[pid: 243|app: 0|req: 18/56] 127.0.0.1 () {52 vars in 843 bytes} [Wed Feb 17 22:04:49 2016] POST /clouds => generated 17 bytes in 13 msecs (HTTP/1.1 503) 2 headers in 96 bytes (1 switches on core 0)
`

This is the message I get when trying to connect a local vcenter instance with mist.io. The username, IP and password provided in mist.io GUI is correct. However, the addition fails.

**Comment by mgogoulos** [comment]
Something went wrong here, let us have a look why.

Cheers,
Markos

**Comment by mgogoulos** [comment]
Please have a look on http://docs.mist.io/article/73-adding-vsphere and let us know if it can connect.

Cheers,
Markos

**Comment by kilokill** [comment]
@mgogoulos I followed the instructions there and that is how I get the error posted above.

**Comment by mgogoulos** [comment]
Hi, do you use a self signed certificate? This might be the problem. Edit file src/mist/io/methods.py and on  connect_provider() function, replace

```
    elif cloud.provider == Provider.VSPHERE:
        conn = driver(host=cloud.apiurl, username=cloud.apikey, password=cloud.apisecret)
```

with

```
    elif cloud.provider == Provider.VSPHERE:
        libcloud.security.VERIFY_SSL_CERT = False;
        conn = driver(host=cloud.apiurl, username=cloud.apikey, password=cloud.apisecret)
```

What version of vSphere are you using?

**Comment by mgogoulos** [comment]
I've updated the doc http://docs.mist.io/article/73-adding-vsphere and it has a 'common issues' section I believe it can help you to provide the correct credentials. Please have a look and let me know if it works. 

Also you have to restart the services uwsgi and celery after performing the above patch.

```
user@user:~/mist.io$ ./bin/supervisorctl restart uwsgi celery
```

**Comment by kilokill** [comment]
@mgogoulos I tried the above to no luck. Still getting the same error. I am using ESXI 6.0.0 (Build 3029758).. maybe that is the issue given your testing was on esxi 5. And yes, I am using a self-signed certificate.

**Comment by mgogoulos** [comment]
We have also tested the vSphere integration with ESXI 6 and it has been able to connect. I've just tested with our local vSphere, on my browser I load https://vsphere.mist.io/folder and I provide a username/password combination for the page to load. 

So on mist.io I enter the same username/password, along with vsphere.mist.io as hostname and it connects without issues. 

This is a default vSphere 6 installation. It would be helpful if you could pass me some testing account (assuming the the installation is a testing environment) so I can try to authenticate. 

Regards,
Markos

**Comment by mgogoulos** [comment]
Unfortunately this is more complicated than expected...vSphere 6 and self signed certificates won't work unless python 2.7.11+ and pyvmomi 6.0.0+ are installed on the system. Have a look on https://github.com/vmware/pyvmomi/issues/235

I'm going to fix this and commit it, basically on src/libcloud/libcloud/compute/drivers/vsphere.py you need to add these 3 lines

```
    import ssl
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.verify_mode = ssl.CERT_NONE
```

at the beginning of the file, and then on class VSphereNodeDriver.__init__() you have to replace

```
            self.connection = connect.SmartConnect(host=host, user=username,
                                                   pwd=password, sslContext=context)
```

with 

```
        context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
        context.verify_mode = ssl.CERT_NONE
        try:
            self.connection = connect.SmartConnect(host=host, user=username,
                                                   pwd=password, sslContext=context)
            atexit.register(connect.Disconnect, self.connection)
```

This will only work with python 2.7.11 and above. So you have to update python if you are using an earlier version (eg 2.7.6 on Ubuntu 14).

**Comment by kilokill** [comment]
Hmm.. let me try the above and get back to you.

**Comment by kilokill** [comment]
So, compiling and running mist.io on Python 2.7.11+ gives me this error
```
Loading paste environment: config:/home/mist/mist.io/uwsgi.ini
2016-02-27 00:28:44,524 WARNING MainThread config - <module>: No settings.py file found.
Traceback (most recent call last):
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/mist/mist.io/src/mist/io/__init__.py", line 81, in main
    configurator.scan()
  File "/home/mist/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/config/__init__.py", line 947, in scan
    ignore=ignore)
  File "/home/mist/mist.io/eggs/venusian-1.0-py2.7.egg/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/home/mist/mist.io/src/mist/io/inventory.py", line 1, in <module>
    import mist.io.methods
  File "/home/mist/mist.io/src/mist/io/methods.py", line 55, in <module>
    import mist.io.tasks
  File "/home/mist/mist.io/src/mist/io/tasks.py", line 16, in <module>
    from celery import Celery, Task
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/__init__.py", line 130, in <module>
    from celery import five
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/five.py", line 149, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
  File "/home/mist/mist.io/eggs/kombu-3.0.26-py2.7.egg/kombu/utils/__init__.py", line 19, in <module>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name _uuid_generate_random
```

**Comment by mgogoulos** [comment]
Hi, 

I also noticed this error. Sad, seems there are dependency errors between different versions of python 2.7 (from 2.7.6 to 2.7.11 in my case)

I've solved the above error with updating kombu version through the virtualenv and restarting uwgi/celery services

```
user@user:~/mist.io$ rm eggs/kombu-*
user@user:~/mist.io$ ./bin/pip install kombu==3.0.30
user@user:~/mist.io$ ./bin/supervisorctl restart uwsgi celery
```

Btw I've followed this for my upgrade of python: http://mbless.de/blog/2016/01/09/upgrade-to-python-2711-on-ubuntu-1404-lts.html

Regards,
Markos

**Comment by kilokill** [comment]
@mgogoulos Thanks. I finally have it working. I just wanted to clarify- are you able to spawn new VMs on Vsphere using mist.io or the functionality is limited to just controlling (stop, delete, restart etc) existing VMs on Mist.io?

**Comment by mgogoulos** [comment]
Hi, 

no you can't spawn new VMs on vSphere now, this is something that is missing. We are working towards the total vSphere integration with mist.io and will add improvements and new functionality in the next few months. 

We are thinking of providing a similar way to deploy VMs as we already do for KVM - a.k.a. create new VMs with the  supplied specs and allow cloud-init based deployments (to setup ssh keys but also user related options). 

Your feedback is greatly appreciated on this, are you using vSphere client or some other tool/service? What would comprise of a rock solid VM deployment way for vSphere? 

Thanks and regards

**Comment by perw07** [comment]
There are still problems with this. I have just installed mist.io on Ubuntu 16.04 LTS. I upgraded to kombu==3.0.35 as instructed above to get all processes to run as wanted (problem with "_uuid_generate_random" missing).

I could not get a connection to my local ESXi system (running 5.5) with a self-signed certificate. I finally figured out that it is a problem in src/libcloud/libcloud/compute/drivers/vsphere.py, around line 70 where class VSphereNodeDriver is initialised:

`if 'certificate verify failed' in message:`

This test does not come out true, although i probably should, because if I replaces it with `if True:` everything works as expected.

I'm not good at debugging these things, can someone please come up with the proper patch for this problem?

**Comment by perw07** [comment]
(... and there should probably be a catch-all `raise Exception('Something unexpected happened, please investigate')` instead of just silently failing to create a connection object.)

**Comment by mgogoulos** [comment]
Hi perw07, 

where you able to install mist.io on 16.04 through the buildout system, or using the mist.io docker image? There's a thread that buildout is broken for 16.04 since it uses python3 and mist.io can only run on python2.6 or python2.7. I'd be interested to know

Now there's that issue with ESXi and self signed certificates, and we've found that if you are using python 2.7.11 then it can bypass it using lib ssl's functions that are not available for previous python versions, so with python 2.7.6 for example it will fail complaining that there's a problem with the certificates, but with python 2.7.11 it will be able to bypass it and establish the connection. 

Cheers,
Markos

**Comment by perw07** [comment]
I just followed the installation instructions (virtualenv, buildout). Since there were a lot of text to the terminal, and I wasn't aware that there might be a problem using 16.04, I didn't look to close on the output. There might have been a lot of errors I didn't see.

Starting the system using supervisord gave the errors earlier in this thread (_uuid_generate_random ...., see earlier comments) that I fixed. I then tried to connect to my stand-alone ESXi, which failed. That is the background to my earlier remarks on fixes needed in src/libcloud/libcloud/compute/drivers/vsphere.py.

Now for the question on python versions:
perw@mist-io-tmp:~$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l

perw@mist-io-tmp:~$ ls -l /usr/bin/python
lrwxrwxrwx 1 root root 9 Dec 10  2015 /usr/bin/python -> python2.7

It turns out that this is the same version (2.7.12) as the python in virtualenv.


Was this any help?

**Comment by mgogoulos** [comment]
So it is on python 2.7 this is why mist.io buildout finished - with some help from your side. 

Thanks!

**Comment by Cougar** [comment]
I just tried latest docker container and added connection with vCenter 6.0.0. mist.io did detect 5 machines out of  83. One of them is configured under resource pool, other four are not. One of them is running (not in resource pool), other four are stopped. Looks strange for me..

**Comment by jpstaub** [comment]
I also had a problem with machine detection. Clone VMs were recognized while parent VMs were not. This may be the same problem in your case. If it is the same problem you might try the following to diagnose/fix:

1. Choose a parent and clone set of VMs
2. Open the vmx files for the parent and clone (vmx files can be found at: datastore_for_vm >> directory_for_vm) 
3. Find and compare vc.UUID of the parent and clone
4. If the vc.UUID's are the same for the parent and clone change the clone vc.UUID by an arbitrary amount. It appears vc.UUID is what mist.io uses to identify vSphere VM's. 
5. Reboot the host
6. mist.io should now recognize the parent and clone.

While uuid.bios and uuid.location are unique for clones, for some reason, vSphere does not produce a unique vc.UUID; at least not when clones are made manually. I don't have the big bucks to buy vCenter to find out whether the same is true if clones are manufactured by machine.

mgogoulos: If vc.UUID was chosen arbitrarily to ID/control VMs it would be worth evaluating whether or not uuid.bios or uuid.location could be used to achieve the same objective(s). That way people wouldn't be exposed to what is a vSphere annoyance. 

Regards,
Jake

**Comment by yevgeniyo** [comment]
Hi guys, quick question, can mist connect to esx directly? Or it should be vcenter?

**Comment by yevgeniyo** [comment]
Hi guys, I also have the same issue like @perw07 with the same environment, I've connected to ESX but now I cant perform any action (shut down/up etc).... Is any solution for it?

**Comment by yevgeniyo** [comment]
Skip my question, I printed exception and saw this line:
'Current license or ESXi version prohibits execution of the requested operation.'

**Comment by duel007** [comment]
Same issue for me as @Cougar. Only showing 5 vms total out of 100+ and apparently can't do anything else?

**Comment by mgogoulos** [comment]
Hi, 

I need temporary access to a vSphere environment that has this behavior, if anyone can provide me with a temporary guest account for a few hours I believe I can sort this issue. 

mgogoulos@mist.io

**Comment by mgogoulos** [comment]
@Cougar @jpstaub @duel007 can you please ping me on mgogoulos@mist.io,  I can send you some instructions to test a patch - thanks

**Comment by d-mo** [comment]
vSphere support has been enhanced in the latest v3.0.0 version. Please try again and open a new ticket if you find any issues.
