### ISSUE TITLE
LXD/LXC Support

### ISSUE THREAD

**Issue by fang64** [mistio/mist-ce#901]
Are there any future plans to support LXD or LXC containers? Since libvirt is being used, I imagine it wouldn't be out of the realm of question to support.

**Comment by mgogoulos** [comment]
Hi, 

sure, LXC container support is planned for a future release. It's not something we plan to focus for the next few months, unless there's some increasing interest here. 

Cheers

**Comment by s3rj1k** [comment]
HI, I am also interested in this feature.

**Comment by fang64** [comment]
Hello @mgogoulos 

I just wanted to express there is interest in supporting this, I personally leverage LXC via scripted tooling, it would be nice to monitor and manage state of containers on hosts via mist. 

Thanks

**Comment by MichaelSchmidle** [comment]
Would love to see LXD supported, too. +1

**Comment by tylerr92** [comment]
Plus 1 for LXC/LXD support please.

**Comment by jamesponddotco** [comment]
Our entire infrastructure runs on bare metal and LXD, so this would be a godsend. We are willing to pay to speed up support for this feature.

**Comment by cpsaltis** [comment]
We're open to prioritizing this higher. I would like to understand a few things more regarding your needs. I will follow up over email @jamesponddotco.

**Comment by cpsaltis** [comment]
@jamesponddotco we are actively researching this and I have a few questions. Could we arrange a quick chat next week?

**Comment by jamesponddotco** [comment]
@cpsaltis Sure thing, man! I have time on Monday, does that work for you? I replied to your email with the my time table, which should help.

**Comment by jamesponddotco** [comment]
Just to provide an update on this issue, @cpsaltis and I reached and agreement, and LXD support will be added to the platform early next year 🎉

**Comment by d-mo** [comment]
LXD support was added in [v4.3.0](https://github.com/mistio/mist-ce/releases/tag/)
