### ISSUE TITLE
Fail to persist a mist.api.machines.models.Machine with a size attribute of NodeSize.

### ISSUE THREAD

**Issue by adiroiban** [mistio/mist-ce#915]
libcloud.compute.base.Node.size is documented as NodeSize type    https://github.com/apache/libcloud/blob/trunk/libcloud/compute/base.py#L191

but in the mongo definition at api/src/mist/api/machines/models.py the size is defined as `size = me.StringField()`

If a Node is created by the driver with a valid size reference, mist.io fails to persist the node.

I have checked the other libcloud implementation and it looks like they are not using the size attribute when creating a node

To reproduce this, implement a libcloud driver which will generate Node instances which has the size attribute set.

Here is the traceback:

```
api_1                   | Traceback (most recent call last):
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/main/base.py", line 257, in update
api_1                   |     self.compute.check_connection()
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/compute/base.py", line 120, in check_connection
api_1                   |     self.list_machines()
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/compute/base.py", line 304, in list_machines
api_1                   |     "errors": exc.to_dict()})
api_1                   | BadRequestError: Bad Request: {'msg': u"ValidationError (Machine:2335228ad43e4a9c925bf0f1b3182aa5) (StringField only accepts string values: ['size'])", 'errors': {'size': u'StringField only accepts string values'}}
```

**Comment by mgogoulos** [comment]
Hi,
The machine model is defined on src/mist/api/machines/models.py. As you've already noticed size is stored as string, not as libcloud's NodeSize. The machine model stores information regarding a machine and amongst other information, a few of the properties of a libcloud Node are included. 

But it does not save the whole libcloud Node object (similarly no NodeSize, or NodeImage objects)

**Comment by adiroiban** [comment]
So the db should store the NodeSize `id`.
I think that a patch is 

```
$ git di src/mist/api/machines/models.py
diff --git a/src/mist/api/machines/models.py b/src/mist/api/machines/models.py
index 2256375..84822ff 100644
--- a/src/mist/api/machines/models.py
+++ b/src/mist/api/machines/models.py
@@ -216,7 +216,7 @@ class Machine(me.Document):
             'extra': self.extra,
             'cost': self.cost.as_dict(),
             'image_id': self.image_id,
-            'size': self.size,
+            'size': self.size.id,
             'state': self.state,
             'tags': tags,
             'monitoring': self.monitoring.as_dict() if self.monitoring else '',
```

it is still not clear how I should create a PR for this change.

Any advice?

Thanks!

**Comment by d-mo** [comment]
This has been fixed.
