### ISSUE TITLE
adduser: adding docker cloud (--docker-cloud) fail

### ISSUE THREAD

**Issue by evilp** [mistio/mist-ce#917]
when i try to add the docker host via the adduser command, and --docker-cloud parameter, it fails with an error. my steps:
docker-compose exec api sh
./bin/adduser --docker-cloud --admin admin@example.org

output:

> MIST_API_DIR is /mist.api
> Couldn't find core config in /mist/core/config.py
> Reading settings from environmental variables.
> Reading local settings from /etc/mist.io/settings.py
> 2017-09-03 14:04:57 INFO MainThread __init__ - mongo_connect: Attempting to connect to mist2 at mongodb:27017...
> 2017-09-03 14:04:57 INFO MainThread __init__ - mongo_connect: Connected...
> Arguments: Namespace(admin=True, docker_cloud=True, email='admin@example.org', org=None, password=False)
> Will create user
> Password: 
> Setting user password.
> Setting user to admin.
> Will create new org
> Adding/Updating docker host cloud
> 2017-09-03 14:05:07 ERROR MainThread base - list_machines: Error while running list_nodes on <class 'mist.api.clouds.models.DockerCloud'> cloud Mist Docker (9c7d35a42ec4452dbf265d3fe54ab3b0) of Org admin@example.org (1 teams - 1 members)
> Traceback (most recent call last):
>   File "/mist.api/src/mist/api/clouds/controllers/compute/base.py", line 160, in list_machines
>     nodes = self._list_machines__fetch_machines()
>   File "/mist.api/src/mist/api/clouds/controllers/compute/controllers.py", line 817, in _list_machines__fetch_machines
>     if is_private_subnet(host):
>   File "/mist.api/libcloud/libcloud/utils/networking.py", line 42, in is_private_subnet
>     ip = struct.unpack('I', socket.inet_aton(ip))[0]
> error: illegal IP address string passed to inet_aton
> 2017-09-03 14:05:07 ERROR MainThread base - update: Will not update cloud <class 'mist.api.clouds.models.DockerCloud'> cloud Mist Docker (9c7d35a42ec4452dbf265d3fe54ab3b0) of Org admin@example.org (1 teams - 1 members) because we couldn't connect: CloudUnavailableError('Cloud unavailable',)
> Error adding docker cloud: CloudUnavailableError('Cloud unavailable',)
> 

:

**Comment by mgogoulos** [comment]
Hi,

cannot reproduce, just tried with the latest version and the Docker cloud is added. What version are you trying?

**Comment by evilp** [comment]
Hi,

tried with version 2.1.0
Updated now to latest (2.2.1) and now the error when using adduser is gone :-)

Btw. i have to update the elasticsearch image to v5.3.1 because there's a bug in v5.2.1 with cgroups on some linux distros, see here: https://github.com/elastic/elasticsearch/issues/23486
