### ISSUE TITLE
Using Mist with localhost libvirtd

### ISSUE THREAD

**Issue by gnd** [mistio/mist-ce#920]
I have a problem configuring dockerized Mist to use a local connection to libvirtd. 
I have changed the settings.py file to contain:

ALLOW_LIBVIRT_LOCALHOST = True

and i get a "Cloud unavailable: Connection error". The libvirt-sock permissions are OK and docker should be able to connect.

(BTW. apparently having just "ALLOW_CONNECT_LOCALHOST = True" doesnt do the job, as mist requires the former)

**Comment by mgogoulos** [comment]
Hi, 

same as on https://github.com/mistio/mist.io/issues/916 , you can either specify the ip of the interface where KVM listens (eg 192.168.122.1, for virbr0 on Ubuntu) or also 172.17.0.1 where is the ip of the docker0 interface.

**Comment by mgogoulos** [comment]
both are valid,  your mist.io installation can communicate with these ips, since they are accessible
