### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by mahamed91** [mistio/mist-ce#922]
Hello

So i installed mist.io by following the instruction on the page and I'm getting a a 502 error.

Anything I can do to fix that?

https://i.imgur.com/2kTnYxK.png

That's running on Ubuntu 16.04 LTS

**Comment by mgogoulos** [comment]
Hi, 

are containers running? Can you paste the output of 
```docker-compose ps```  and also system specs? (cpu/ram/disk)

**Comment by mahamed91** [comment]
Hi

They are running.

[https://i.imgur.com/qDrUSew.png](url)

It's a VPS with 1vCpu + 1 GB Ram and 20GB disk space. I know it's far lower than the recommended specs, but I still have the issue when I used a much more powerful server. Even if I dont meet system requirements it shouldn't fail outright.

**Comment by mgogoulos** [comment]
Hi, 
on the screenshot I see many containers that have exited. You can check the logs and see why this happens, eg check why api and celery are not running (mist.io won't function at all without these)

```docker-compose logs -f api celery```

but this is definitely due to the low specs of the server. 

If not all containers are running after you run ```docker-compose up``` then check the logs of those that are not running, and paste the output so we can see if there's an issue here. 

Cheers

**Comment by mahamed91** [comment]
Hi

I'll look into the api and celery logs. Also, I'm going fire up a more
powerful vps tomorrow and send all the logs tomorrow from both VPS around
1500 UTC.

Thanks


On 23 Sep 2017 11:14, "Markos Gogoulos" <notifications@github.com> wrote:

Hi,
on the screenshot I see many containers that have exited. You can check the
logs and see why this happens, eg check why api and celery are not running (
mist.io won't function at all without these)

docker-compose logs -f api celery

but this is definitely due to the low specs of the server.

If not all containers are running after you run docker-compose up then
check the logs of those that are not running, and paste the output so we
can see if there's an issue here.

Cheers

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mistio/mist.io/issues/922#issuecomment-331624635>, or mute
the thread

**Comment by mahamed91** [comment]
Hello

So you were right about the low specs of the system, but I'm going to investigate it again on a more powerful server and look at the logs.

I piped `docker-compose up` to a file and this snippet in the link repeats for a most of the document till I stopped the process.

https://imgur.com/1ID1vvd

[logs.txt](https://github.com/mistio/mist.io/files/1326897/logs.txt)

**Comment by mahamed91** [comment]
Hello

So yeah, it works. The RAM wasn't enough.

I'll close the issue, but I'm going to type up a quick troubleshooting check list and i hope that you can add it to the running mist.io page in the docs.

https://i.imgur.com/wvFI9N4.png

Thanks

**Comment by mgogoulos** [comment]
Hi, 

please do create the list, that would be helpful for other people as well!
