### ISSUE TITLE
KVM Provider: When Starting VMs the VM is launched but its never available

### ISSUE THREAD

**Issue by paxsonsa** [mistio/mist-ce#925]
Using the latest release tag for mistio. I successfully got mistio to work on the localhost KVM. A problem has occurred when starting a machine.

I have selected a ubuntu xenial version image.  When the all the fields are filled in I deployed the machine. The machine appears to be working but what becomes apparent is that the machine is not available. Its CPUs are maxed at 100%. I waited up to 30min but the machine was not available. 

using `arp -an` I couldn't see its ip address either. 
using virtual machine manager, I can see the machine is turned on and its CPU is maxed out. 

Not sure how to debug this one. Creating a VM with the same image using VM manager work perfectly fine.

**Comment by paxsonsa** [comment]
Closing Issue, we have moved on to another tool, unfortunately. We are still experiencing the issue so feel free to reach out if you are interested.

**Comment by cpsaltis** [comment]
@paxsonsa thanks a lot for offering help. 

To make sure I get this right, you have a KVM host running. You installed Mist.io there. Then you connected to Mist.io web interface and you connected the same KVM host as a "KVM cloud". Once this was done you tried to provision a VM on the same host using the official xenial image.

Are these correct?

What are the specs of your host (CPU/RAM/Disk)?

Also, could you please dump the xml for the VM you provisioned and share it?

**Comment by paxsonsa** [comment]
Sorry for the delay!

That is all correct. In fact I was able to track down the issue and it is NOT a mistio. I apologize if I came across the wrong way. 
It appears it has to do with the ubuntu cloud image. If there is no isa-serial device attached to the VM then ubuntu will not boot. 
#### Mistio Created XML
[mistio.xml.txt](https://github.com/mistio/mist.io/files/1625065/mistio.xml.txt)

#### Ubuntu Image
https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img

#### Image Result of it running inital and the cpu are 100%:
![screenshot from 2018-01-11 22-00-37](https://user-images.githubusercontent.com/13216842/34861734-6f09a630-f71b-11e7-9d37-6069959a5e7f.png)

#### Looking at the hardware setup you can see no console/serial.
![screenshot from 2018-01-11 22-01-06](https://user-images.githubusercontent.com/13216842/34861758-94346418-f71b-11e7-8641-a814354ff2a8.png)

#### Add isa-serial to vm
![screenshot from 2018-01-11 22-01-29](https://user-images.githubusercontent.com/13216842/34861786-a9975658-f71b-11e7-92e5-5fe2a990a5ab.png)
![screenshot from 2018-01-11 22-01-29](https://user-images.githubusercontent.com/13216842/34861809-bbfdbcce-f71b-11e7-9e00-729af06c2352.png)

#### New XML 
[mistio_with_serial.xml.txt](https://github.com/mistio/mist.io/files/1625075/mistio_with_serial.xml.txt)

#### New CPU Usage of VM (after about 5sec)
![screenshot from 2018-01-11 22-03-39](https://user-images.githubusercontent.com/13216842/34861901-383cdeaa-f71c-11e7-882d-0d025a8d6ced.png)

**Comment by paxsonsa** [comment]
It does appear that the KVM provider with mistio might need to have some ability to add interfaces? Though that might be outside the scope of what mistio should do?

**Comment by cpsaltis** [comment]
Thanks a lot for the detailed report @paxsonsa.

We're working on a fix on the tty issue. We're also working as we speak on adding bridged networking to KVM.

I'll leave this ticket open until those get released and I'll notify you when the do.

**Comment by paxsonsa** [comment]
@cpsaltis thanks very much let me know if there is anything I can do to help!

**Comment by d-mo** [comment]
[v4.3.0](https://github.com/mistio/mist-ce/releases/tag/) includes many improvements regarding KVM support. You may want to try again.
