### ISSUE TITLE
Assigning OpenStack Floating IPs

### ISSUE THREAD

**Issue by dizz** [mistio/mist-ce#929]
Hi,

I'm currently experimenting with the community edition of Mist.io. The Mist.io stack is running on one node and is connected to 3 different clouds, 2 OpenStack and 1 EC2.

Currently the two OpenStack installations registered successfully (our own internal and an external one (engines.switch.ch)). On each, allocating a floating IP does not happen, however the creation of the VM and assignment of the private IP does. On EC2 (by default) there's a public IP assigned.

How can I debug the issue related to floating IP assignment? What specific container should I look at and get the logs from? Do I need to enable debug logging and if so how is this done?

Happy to provide more details where it helps!

**Comment by d-mo** [comment]
The issue regarding floating IP assignment in Openstack has been fixed in the staging branch. The fix will be included in the upcoming release, probably by the end of next week. In the meantime you can try out with a development deployment of Mist.io from the staging branch. Before firing it up you will need to recursively update the git submodules `git submodule update --init --recursive`. Please let us know if it works for you.

**Comment by dizz** [comment]
Thanks! I’ll give that a go and let you know how it works out 👍

**Comment by dizz** [comment]
So I've tried to run staging. The stack comes up fine. I then register two OpenStack deployments (one belong to us and another: engines.switch.ch). On our deployment the floating IP association now works 😃, however on the SWITCH deployment it does not. SWITCH's network setup is different to our (they enable ipv6 along side ipv4 by default), however when mistio has the SWITCH deployment registered it does not retrieve the list of networks available on SWITCH (the neutron endpoint is listed as available and responds to a python requests GET).

If you want I can supply the docker-compose log file. Let me know, otherwise thanks for the help so far!

**Comment by d-mo** [comment]
Sorry for the delay. If there's a traceback in the logs that seems relevant please send it over. It sounds like the remaining issue is related to the setup of that environment. Keep in mind that Mist.io does not currently support ipv6.

**Comment by dizz** [comment]
@d-mo doh! I had deleted it only yesterday. I'll recreate the setup and get the logs for you. FYI: the SWITCH setup has both IPv6 and IPv4 enabled by default, however when I create an IPv4 only network the floating IP is not allocated. Nonetheless I'll get the logs over to you.
