### ISSUE TITLE
OpenStack: Support for keystone V3

### ISSUE THREAD

**Issue by garelp** [mistio/mist-ce#931]
Hello,

I'm trying to use an public OpenStack cloud, but it uses Keystone V3 and domains.. I can put this information currently in the config fields.. Is there a way to use keystone V3?? or it's on the roadmap somewhere??

Thanks.

**Comment by d-mo** [comment]
Unfortunately Keystone V3 is not yet supported. It is on the roadmap but it's not clear when it will become a priority for the dev team.

**Comment by imakiro** [comment]
Hello,

Does https://blog.mist.io/post/186539734686/mist-now-supports-alibaba-cloud indicates that Keystone V3 is supported? 
If so, there is no way in the "add cloud" form to specify OS_PROJECT_ID and OS_USER_DOMAIN_ID on which it can rely. Is this still WIP ?

**Comment by d-mo** [comment]
Yes, it is now supported AFAICT, at least partially. We forgot to update this ticket.

OS_PROJECT_ID should be the same as the tenant name which can be specified in the add cloud form.

OS_USER_DOMAIN_ID on the other hand is a new parameter that's not supported by Mist. The default value for that should be "default" from what I see in the OpenStack docs. Is this something you need to customize in your setup? It shouldn't be hard to add it in the upcoming v4.2.0 release, however we don't have an environment with multiple authentication domains in order to test it. Would you mind testing it a beta release against your environment in about a week from now?

**Comment by imakiro** [comment]
> `OS_PROJECT_ID should be the same as the tenant name which can be specified in the add cloud form.`
Unfortunately not in all of Huawei's Openstack based cloud solutions, ability to set both fields are mandatory for this.
If you have a beta in the form of a docker-compose file, I'm up for it, just let me know how to grab the appropriate version, how to send you logs if it doesn't work (or point me to where it's indicated for beta versions) and sure I'll test as soon as it's available.

**Comment by d-mo** [comment]
Hi @imakiro. Can you try out the latest beta release? It introduces a new `Domain Name` field when adding OpenStack clouds https://github.com/mistio/mist-ce/releases/tag/v4.2.0-beta.5

If it doesn't work, please send me the output of the command `docker-compose logs api`.

Unfortunately Apache Libcloud doesn't currently allow to set custom versions for the image & network API's. Mist will try to use the v2 API's for compute, image & network and v3 for identity. If you're running OpenStack environments with different requirements, I'd like to know more about them to see how Mist can better support them. Perhaps over a quick call?

**Comment by imakiro** [comment]
It works, with this information, mist now connects to the cloud (Huawei Public Cloud / Flexible Engine / FusionCompute derivatives)

**Comment by cpsaltis** [comment]
@imakiro it's the first time we see a Huawei user and I'd love to learn a bit more. Would you be available for a quick call in the coming days?

**Comment by imakiro** [comment]
> 
> 
> @imakiro it's the first time we see a Huawei user and I'd love to learn a bit more. Would you be available for a quick call in the coming days?

Sure, no problem, ping me on twitter:@kuzko_topia , i'll give you more on there

**Comment by cpsaltis** [comment]
ok perfect. I just reached out with a private message for our mist_io account. Talk to you there @imakiro
