### ISSUE TITLE
Add KVM (via libvirt) Cloud - Bad Request Error

### ISSUE THREAD

**Issue by AndreasWidmer** [mistio/mist-ce#932]
Hi, I want to add a local KVM via libvirt.
I changed the settings.py to allow localhost and use the IP 192.168.122.1 as the KVM Hostname.
All the other fields (except name & datastore for iso files) are empty. When I click the button to Add the cloud, I get the following error:
`
Bad Request: {'msg': u"ValidationError (Cloud.LibvirtCloud:6c4cc19b19364640ae01d33ab91aef50) ( could not be converted to int: ['port'] A ReferenceField only accepts DBRef, ObjectId or documents: ['key'])", 'errors': {'port': u' could not be converted to int', 'key': u'A ReferenceField only accepts DBRef, ObjectId or documents'}}`

Debian 9
Docker version 18.03.0-ce, build 0520e24
Latest stable mist.io from docker 

What can I do?
Thanks!

**Comment by cpsaltis** [comment]
Hi Andreas,

Thanks for reporting this and sorry for the trouble.

Could you please clarify if you followed the instructions at https://github.com/mistio/mist.io/releases/tag/v2.6.0?

Docker hub also hosts a deprecated image of Mist.io and I want to make sure we're talking about the same thing.

**Comment by d-mo** [comment]
Hi Andreas,

please try again using the latest v3.1.0 release. The support for KVM has been enhanced significantly. If this is still a problem for you please reopen the issue.
