### ISSUE TITLE
Insecure HTTP Listener Binding All Ports

### ISSUE THREAD

**Issue by phrag** [mistio/mist-ce#933]
Similar, mist-ce binds to 0.0.0.0:80, not localhost as specified.

Please consider including https://hub.docker.com/r/linuxserver/letsencrypt/

Configuring a cloud platform like mist which has root access to all your VMs / clouds without HTTPS is rather irresponsible. Logging into this over the internet is a terrible idea.

It's easy to setup nginx with letsencrypt to proxy the web interface.

**Comment by d-mo** [comment]
Indeed, HTTPS configuration is currently left as an exercise to the end user. We've discussed about adding letsencrypt support and we all agree it's a great idea, that hasn't made it to the top of priorities just yet. We'd love to see some help from the wider community on this.

**Comment by phrag** [comment]
I believe including https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/ would suffice alongside the existing nginx component.

**Comment by d-mo** [comment]
v3.1.0 comes with instructions on setting up TLS https://github.com/mistio/mist-ce#tls-settings

We're still considering how to automate the issuing and renewing of certificates with letsencrypt. Unfortunately it's not trivial to do it in a foolproof way that doesn't require manual configuration from the user.
