### ISSUE TITLE
API Exit Code 22

### ISSUE THREAD

**Issue by bimmer7410** [mistio/mist-ce#936]
I've been attempting to get this running for the past few hours, and have narrrowed down the issue to the API_1 service. When it attempts to start, I get a exception and it begins its startup loop again and again.. 

`api_1                   | *** Operational MODE: preforking ***
api_1                   | Loading paste environment: config:/mist.api/uwsgi.ini
api_1                   | Traceback (most recent call last):
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
api_1                   |     return loadobj(APP, uri, name=name, **kw)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
api_1                   |     global_conf=global_conf)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
api_1                   |     global_conf=global_conf)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
api_1                   |     return loader.get_context(object_type, name, global_conf)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
api_1                   |     section)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
api_1                   |     object_type, name=use, global_conf=global_conf)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
api_1                   |     global_conf=global_conf)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
api_1                   |     global_conf=global_conf)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
api_1                   |     return loader.get_context(object_type, name, global_conf)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
api_1                   |     object_type, name=name)
api_1                   |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
api_1                   |     pkg_resources.require(self.spec)
api_1                   |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
api_1                   |     needed = self.resolve(parse_requirements(requirements))
api_1                   |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 837, in resolve
api_1                   |     new_requirements = dist.requires(req.extras)[::-1]
api_1                   |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2489, in requires
api_1                   |     dm = self._dep_map
api_1                   |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2713, in _dep_map
api_1                   |     self.__dep_map = self._compute_dependencies()
api_1                   |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2722, in _compute_dependencies
api_1                   |     for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
api_1                   |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2704, in _parsed_pkg_info
api_1                   |     metadata = self.get_metadata(self.PKG_INFO)
api_1                   |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1870, in get_metadata
api_1                   |     raise KeyError("No metadata except PKG-INFO is available")
api_1                   | KeyError: 'No metadata except PKG-INFO is available'
`

This is a fresh CentOS 7 install with the latest Docker, Docker-compose, and  3.10.0-862.3.3.el7.x86_64 kernel. SELinux has been disabled, and there are no services running on ports besides 22 and 25.

**Comment by cnskyhigh** [comment]
I also meet the same problem, looks like the problem for your docker image for 'api' as I change the code to the tag 'v3.1.0', it still not work.
```
api_1                   | + unset JS_BUILD
api_1                   | + echo {"sha":"7e9f6a990a09e3bed4137bbf987dd8f919e86f7a","name":"staging","repo":"mistio/mist.io","modified":true}
api_1                   | + pip install -e /mist.api/bin/../paramiko/
api_1                   | Obtaining file:///mist.api/paramiko
api_1                   | Requirement already satisfied: cryptography>=1.1 in /usr/lib/python2.7/site-packages (from paramiko==2.0.3) (1.8.1)
api_1                   | Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko==2.0.3) (0.2.3)
api_1                   | Requirement already satisfied: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.0.3) (2.5)
api_1                   | Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.0.3) (0.22.0)
api_1                   | Requirement already satisfied: packaging in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.0.3) (16.8)
api_1                   | Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.0.3) (1.11.0)
api_1                   | Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.0.3) (39.2.0)
api_1                   | Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.0.3) (1.1.6)
api_1                   | Requirement already satisfied: ipaddress in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.0.3) (1.0.18)
api_1                   | Requirement already satisfied: cffi>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.0.3) (1.10.0)
api_1                   | Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging->cryptography>=1.1->paramiko==2.0.3) (2.2.0)
api_1                   | Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko==2.0.3) (2.17)
api_1                   | Exception:
api_1                   | Traceback (most recent call last):
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
api_1                   |     status = self.run(options, args)
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 318, in run
api_1                   |     self._warn_about_conflicts(to_install)
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 442, in _warn_about_conflicts
api_1                   |     package_set, _dep_info = check_install_conflicts(to_install)
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_internal/operations/check.py", line 89, in check_install_conflicts
api_1                   |     state = create_package_set_from_installed()
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_internal/operations/check.py", line 39, in create_package_set_from_installed
api_1                   |     retval[name] = PackageDetails(dist.version, dist.requires())
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2613, in requires
api_1                   |     dm = self._dep_map
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2864, in _dep_map
api_1                   |     self.__dep_map = self._compute_dependencies()
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2873, in _compute_dependencies
api_1                   |     for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2855, in _parsed_pkg_info
api_1                   |     metadata = self.get_metadata(self.PKG_INFO)
api_1                   |   File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1794, in get_metadata
api_1                   |     raise KeyError("No metadata except PKG-INFO is available")
api_1                   | KeyError: 'No metadata except PKG-INFO is available'
api_1                   | You are using pip version 10.0.1, however version 18.0 is available.
api_1                   | You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by d-mo** [comment]
Please try with Mist v4.2.0 and reopen if this is still an issue.
