### ISSUE TITLE
how to add Kubernetes provider to mistio-ce

### ISSUE THREAD

**Issue by angry-tony** [mistio/mist-ce#939]
Hello,

I'm trying to use Kubernetes, but I can not see it in " CHOOSE A PROVIDER " UI.
in official "mist.io " web site, i can see Kubernetes in "Supported Providers List"
is it possible to use Kubernetes as a provider??

Thanks.

**Comment by cpsaltis** [comment]
Our Enterprise and Hosted Editions support management of k8s at the cluster level, e.g. provisioning, scaling up & down clusters etc. This is not part of the Community Edition here.
