### ISSUE TITLE
Adding KVM (via libvirt) - Bad Request Error

### ISSUE THREAD

**Issue by mayankasthana** [mistio/mist-ce#942]
Same as #932.

I am using the hostname as 172.17.0.1 and all SSH related fields are blank.

Getting the error

```
Bad Request: {'msg': u"ValidationError (Cloud.LibvirtCloud:7fd99dba76b14c5c90b859798de19162) ( could not be converted to int: ['port'] A ReferenceField only accepts DBRef, LazyReference, ObjectId or documents: ['key'])", 'errors': {'port': u' could not be converted to int', 'key': u'A ReferenceField only accepts DBRef, LazyReference, ObjectId or documents'}}
```

**Version**
Release v3.3.1

**System info**
Docker version: 18.06.1-ce
Storage Driver: zfs
Kernel Version: 4.15.0-39-generic
Operating System: Ubuntu 18.04.1 LTS

**Comment by BeyondDefinition** [comment]
I have the same issue, using hostname 'localhost', as I want to connect to local libvirtd.

`Bad Request: {'msg': u"ValidationError (Cloud.LibvirtCloud:ad05c83ec82b46b1a7d298fd0c5cc07a) (A ReferenceField only accepts DBRef, LazyReference, ObjectId or documents: ['key'])", 'errors': {'key': u'A ReferenceField only accepts DBRef, LazyReference, ObjectId or documents'}}`

**Version**
Release v3.3.1

**System info**
Docker version: 18.09.1-ce
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS

**Comment by edtbl76** [comment]
Same issue.

**Comment by d-mo** [comment]
The "localhost" hostname won't work because it will refers to the Mist API container itself. Use instead the local network address of the host (e.g 192.168.1.2). Don't forget to add a valid ssh key for root or a user with passwordless sudo access. Without a valid ssh key the Mist containers will not be able to execute commands on the host.

**Comment by edtbl76** [comment]
Bad Request: {'msg': "ValidationError (Cloud.LibvirtCloud:903bdbf77d42450a90202dffaf9c4a42) ( could not be converted to int: ['port'] A ReferenceField only accepts DBRef, LazyReference, ObjectId or documents: ['key'])", 'errors': {'port': ' could not be converted to int', 'key': 'A ReferenceField only accepts DBRef, LazyReference, ObjectId or documents'}}

This error occurs regardless of whether or not you use the fqdn or ip address. This is an internal bug.

**Comment by CrashSerious** [comment]
So, I struggled with this a bit-- I'm not sure why. It's quite simple and a common task, I guess it just didn't click or wasn't presented in a way that made it click.

When you generate keys in Mist.IO this is teh same as generating keys with ssh-keygen on a client machine when you want to connect password-less to another linux host.

Generate the keys in mist.io, assign the key to the KVM and before you click "Add"-- place the public keys into the /.ssh/authorized_keys file for the user that is root or has sudo access.

**Comment by d-mo** [comment]
This has been fixed. Please re-open if that's not the case.
