### ISSUE TITLE
Invitation emails do not send

### ISSUE THREAD

**Issue by kiplandiles** [mistio/mist-ce#946]
I am testing a pilot of mist.io CE from the latest distro. I cannot seem to get invitation emails to work. I did modify settings.py and setup for Google (we use Google Apps for Work and we can send without authentication from our office network). Below is the snippet from settings.py ...
```
## Configure email settings.
MAILER_SETTINGS = {
     'mail.host': "smtp-relay.gmail.com",
     'mail.port': "25",
     'mail.tls': False,
     'mail.starttls': False,
#     'mail.username': "",
#     'mail.password': "",
}
```
I have tried with and without the username and password commented out. No joy either way. I did do a manual test on that server using **telnet smtp-relay.gmail.com 25** and then all the usual stuff to test a simple non-authenticated relay to Google. That works without issue so the server can send email as it does reside here at our office.

**API Logs**
The were obtained using command: **docker-compose logs --tail=100 -f api**. The ERROR below actually kills the logging.
```
api_1                   | 2018-12-20 23:32:35,963 INFO  [mist.api.views][uWSGIWorker8Core0] Sending invitation to user with email 'kiles@tdstickets.com' for team Owners of org sysops@tdstickets.com with token 3af28d2d44f771a91780161792cc3be97ee16ab018edd6e543987579746d1b4b
api_1                   | [pid: 60|app: 0|req: 240/945] 172.22.0.27 () {44 vars in 1017 bytes} [Thu Dec 20 23:32:35 2018] POST /api/v1/org/6f95f863f3644997af126881c2aeb1b7/teams/fe49c7bfecc44ddc86cf5b858b191605/members => generated 126 bytes in 532 msecs (HTTP/1.0 200) 2 headers in 72 bytes (1 switches on core 0)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

I assume I could likely add users manually using the procedure to add the first admin user but prefer to invite so I don't have to get the user over to my desk so they can type their password.

Is there another log I should be checking? Has anyone else reported this issue?

**Comment by d-mo** [comment]
Did you restart the containers after editing the settings.py? You need to restart at least the celery-prefork service for any changes on the MAILER_SETTINGS to take effect. The celery-prefork log may also contain more information regarding the delivery failures.

In any case, you should be able to use the following command to try sending an email through your mist installation:
```
docker-compose exec api python -c "from mist.api import tasks; tasks.send_email('subject', 'body', 'recipient@mail.com', sender='sender@mail.com')"
```

**Comment by d-mo** [comment]
Closing due to lack of response.
