### ISSUE TITLE
docker compose - 'docker-init' no such file errors

### ISSUE THREAD

**Issue by zilkanir** [mistio/mist-ce#948]
Hello,

CentOS Linux release 7.6.1810 (Core) 
docker-1.13.1-88.git07f3374.el7.centos.x86_64
docker-compose version 1.23.1, build b02f1306

I'm recieving the following errors after 'docker-compose up -d' that runs with root.

Any advise?

Thanks,
Nir.

Creating mist-ce_sockjs_1_8238625a0fe2               ... error
Creating mist-ce_cilia_1_61eb396f0dce         ... 
Creating mist-ce_celery-gevent_1_6a156ad7e817 ... 
Creating mist-ce_gocky_1_b639f0c1a148                ... done
Creating mist-ce_scheduler_1_74be15ae8eda     ... 
Creating mist-ce_hubshell_1_778dd05d2a6d      ... 
Creating mist-ce_kibana_1_7e60fecee95c               ... done
Creating mist-ce_scheduler_1_74be15ae8eda            ... error
Creating mist-ce_beat_1_fc689447dffe                 ... 
Creating mist-ce_api_1_f2b752f09a82                  ... 
Creating mist-ce_cilia_1_61eb396f0dce                ... error
Creating mist-ce_poller_1_e615f2841864               ... 
Creating mist-ce_celery-prefork_1_6d3780f713dc       ... 
Creating mist-ce_elasticsearch-manage_1_df9aa58e7825 ... done

Creating mist-ce_api_1_f2b752f09a82                  ... error
ocker-init: no such file or directory"'
Creating mist-ce_celery-gevent_1_6a156ad7e817        ... error
ERROR: for mist-ce_scheduler_1_74be15ae8eda  Cannot start service scheduler: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.apiCreating mist-ce_logstash_1_21c69239a690             ... done

ERROR: for mist-ce_api_1_f2b752f09a82  Cannot start service api: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-Creating mist-ce_apply-migrations_1_da639d10af9f     ... error

ERROR: for mist-ce_cilia_1_61eb396f0dce  Cannot start service cilia: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for mist-ce_apply-migrations_1_da639d10af9f  Cannot start service apply-migrations: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'
Creating mist-ce_hubshell_1_778dd05d2a6d             ... error
ERROR: for mist-ce_celery-gevent_1_6a156ad7e817  Cannot start service celery-gevent: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

Creating mist-ce_celery-prefork_1_6d3780f713dc       ... error
ocker-init: no such file or directory"'
Creating mist-ce_beat_1_fc689447dffe                 ... error
ERROR: for mist-ce_celery-prefork_1_6d3780f713dc  Cannot start service celery-prefork: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for mist-ce_hubshell_1_778dd05d2a6d  Cannot start service hubshell: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for mist-ce_beat_1_fc689447dffe  Cannot start service beat: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for sockjs  Cannot start service sockjs: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for scheduler  Cannot start service scheduler: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for api  Cannot start service api: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for cilia  Cannot start service cilia: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for apply-migrations  Cannot start service apply-migrations: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for celery-gevent  Cannot start service celery-gevent: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for poller  Cannot start service poller: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for celery-prefork  Cannot start service celery-prefork: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for hubshell  Cannot start service hubshell: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'

ERROR: for beat  Cannot start service beat: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/mist.api/bin/docker-init\\": stat /mist.api/bin/docker-init: no such file or directory"'
ERROR: Encountered errors while bringing up the project.

**Comment by tankertux** [comment]
I also encountered this issue with the same errors. I encountered these when I cloned the git repo and ran docker-compose from the cloned directory. Since then, I
followed [the installation instructions ](https://github.com/mistio/mist-ce/releases) for 3.3.1 with success. Are you running the official installation commands?
 `wget https://github.com/mistio/mist-ce/releases/download/v3.3.1/docker-compose.yml
docker-compose up -d`

I am using CentOS Linux release 7.6.1810 (Core)
kernel: Linux 3.10.0-957.1.3.el7.x86_64
Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01

**Comment by poggdogg** [comment]
While looking into another issue I found that the docker-compose.yml version is not being incremented with each change.  This makes it difficult when backtracking versioning problems.

Here's an example:
  elasticsearch-manage:
    image: mistce/elasticsearch-manage:v3-3-1
vs
 elasticsearch-manage:
    image: mistce/elasticsearch-manage:v4-1-1

Both are showing:
version: '2.0'

**Comment by d-mo** [comment]
This is not a Mist bug. We discovered that this happens when someone tries to run `docker-compose up` after cloning the git repo without following the dev installation instructions. If you're affected, please use the published releases instead unless you plan on modifying Mist, in which case you need to follow the respective instructions which will fetch the git submodules among other things.

**Comment by arthurlogilab** [comment]
Got hit by this error too. I understand the fix, but would recommend the project to enable running `docker-compose up -d` from the git checkout (it's now a common way to test out a project from a git clone). Thanks for the fix !
