### ISSUE TITLE
Unable to create KVM machines. 

### ISSUE THREAD

**Issue by codefriar** [mistio/mist-ce#950]
Whenever I try to create a KVM machine I receive the following error:

```console
Creating machine: machine creation finished Machine creation failed: KVM, got exception You have specified /var/lib/libvirt/images/bionic-server-cloudimg-amd64.img as image which does not exist
```

However the file clearly exists, and should be world-readable.

```console
➜  mist l /var/lib/libvirt/images
total 880M
drwxrwxrwx 2 root     root     4.0K Jan 27 03:26 .
drwxr-xr-x 7 root     root     4.0K Jan 25 01:43 ..
-rwxrwxrwx 1 root     root     325M Jan 19 17:38 bionic-server-cloudimg-amd64.img
```

**Comment by codefriar** [comment]
Anyone have ideas?

**Comment by d-mo** [comment]
I think it might be because your ssh user is neither root nor a passwordless sudoer. Try adding the cloud again by providing a root ssh key or by allowing sudo access to your user without requiring a password (NOPASSWD in sudoers file).

I hope that helps. Sorry for the inconvenience. This is a limitation that we should address or at least document better.

**Comment by codefriar** [comment]
> I think it might be because your ssh user is neither root nor a passwordless sudoer. Try adding the cloud again by providing a root ssh key or by allowing sudo access to your user without requiring a password (NOPASSWD in sudoers file).
> 
> I hope that helps. Sorry for the inconvenience. This is a limitation that we should address or at least document better.

so, my user has NOPASSWD in the sudoers file.

**Comment by roddines** [comment]
I can also report this show stopper is still around!

**Comment by d-mo** [comment]
[v4.3.0](https://github.com/mistio/mist-ce/releases/tag/) includes many improvements regarding KVM support.
