### ISSUE TITLE
Web-UI not displayed

### ISSUE THREAD

**Issue by laurentandrian** [mistio/mist-ce#951]
I installed mist-ce 4.0 and followed the instructions:

When I try to access http://<host-address>:80
I see a blank page.

I looked into logs : docker-compose logs --tail=50  celery-prefork
Only error I see:

celery-prefork_1        | The system cannot communicate with the external server (&nbsp;www.traefik.com&nbsp;).
celery-prefork_1        | The Internet server may be busy, may be permanently down, or may be
celery-prefork_1        | unreachable because of network problems.
celery-prefork_1        | </p>
celery-prefork_1        |

is it related ?
My system requires a proxy to connect to internet.

**Comment by d-mo** [comment]
Did you install the latest release using wget according to the instructions in the release page? If you'd like to setup a dev installation using git, there are a few additional required steps that need to be properly documented or automated.

If you're following the standard installation instructions, can you confirm that all containers are up and running with `docker-compose ps`? What's the http response?

**Comment by laurentandrian** [comment]
I downloaded using wget and followed the instructions.

Here is what I see:
[root@manager Mist-IO]# docker-compose ps
             Name                           Command               State                                Ports
----------------------------------------------------------------------------------------------------------------------------------------
mist-io_api_1                    /mist.api/bin/docker-init  ...   Up       80/tcp
mist-io_apply-migrations_1       /mist.api/bin/docker-init  ...   Exit 0
mist-io_beat_1                   /mist.api/bin/docker-init  ...   Up
mist-io_celery-gevent_1          /mist.api/bin/docker-init  ...   Up
mist-io_celery-prefork_1         /mist.api/bin/docker-init  ...   Up
mist-io_cilia_1                  /mist.api/bin/docker-init  ...   Up
mist-io_elasticsearch-manage_1   ./scripts/add_templates.py       Exit 0
mist-io_elasticsearch_1          /docker-entrypoint.sh elas ...   Up       9200/tcp, 9300/tcp
mist-io_gocky_1                  /go/src/github.com/mistio/ ...   Up       0.0.0.0:9096->9096/tcp, 0.0.0.0:9097->9097/tcp
mist-io_hubshell_1               /mist.api/bin/docker-init  ...   Up
mist-io_influxdb_1               /entrypoint.sh influxd           Up       0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp
mist-io_kibana_1                 /docker-entrypoint.sh kibana     Up       5601/tcp
mist-io_landing_1                sh /entry.sh                     Up       80/tcp
mist-io_logstash_1               /docker-entrypoint.sh logs ...   Up
mist-io_mailmock_1               twistd -n localmail --smtp ...   Up       8025/tcp
mist-io_memcached_1              docker-entrypoint.sh memcached   Up       11211/tcp
mist-io_mongodb_1                docker-entrypoint.sh mongod      Up       27017/tcp
mist-io_nginx_1                  nginx -g daemon off;             Up       0.0.0.0:80->80/tcp
mist-io_poller_1                 /mist.api/bin/docker-init  ...   Up
mist-io_rabbitmq_1               docker-entrypoint.sh rabbi ...   Up       15671/tcp, 15672/tcp, 25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp
mist-io_scheduler_1              /mist.api/bin/docker-init  ...   Up
mist-io_socat_1                  socat TCP4-LISTEN:2375,for ...   Up       2375/tcp
mist-io_sockjs_1                 /mist.api/bin/docker-init  ...   Up       8081/tcp
mist-io_swagger_1                sh /usr/share/nginx/docker ...   Up       8080/tcp
mist-io_traefik_1                /traefik --accesslog --api ...   Up       0.0.0.0:8040->80/tcp, 0.0.0.0:8041->8080/tcp
mist-io_ui_1                     sh /entry.sh                     Up       80/tcp

and trying locally with wget:
[root@manager Mist-IO]# wget http://localhost
--2019-03-01 12:11:42--  http://localhost/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1557 (1.5K) [text/html]
Saving to: ‘index.html.1’

100%[========================================================================================================================================================>] 1,557       --.-K/s   in 0s

2019-03-01 12:11:42 (63.7 MB/s) - ‘index.html.1’ saved [1557/1557]

[root@manager Mist-IO]# more index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<script type="text/javascript">
function getCookie(c_name) { // Local function for getting a cookie value
    if (document.cookie.length > 0) {
        c_start = document.cookie.indexOf(c_name + "=");
        if (c_start!=-1) {
        c_start=c_start + c_name.length + 1;
        c_end=document.cookie.indexOf(";", c_start);

        if (c_end==-1)
            c_end = document.cookie.length;

        return unescape(document.cookie.substring(c_start,c_end));
        }
    }
    return "";
}
function setCookie(c_name, value, expiredays) { // Local function for setting a value of a cookie
    var exdate = new Date();
    exdate.setDate(exdate.getDate()+expiredays);
    document.cookie = c_name + "=" + escape(value) + ((expiredays==null) ? "" : ";expires=" + exdate.toGMTString()) + ";path=/";
}
function getHostUri() {
    var loc = document.location;
    return loc.toString();
}
setCookie('YPF8827340282Jdskjhfiw_928937459182JAX666', '64.102.255.40', 10);
try {
    location.reload(true);
} catch (err1) {
    try {
        location.reload();
    } catch (err2) {
    	location.href = getHostUri();
    }
}
</script>
</head>
<body>
<noscript>This site requires JavaScript and Cookies to be enabled. Please change your browser settings or upgrade your browser.</noscript>
</body>
</html>

**Comment by d-mo** [comment]
This html response doesn't seem to be originating from Mist's nginx. Perhaps there was some other process already listening to port 80 on localhost? Instead of http://localhost, try using the ip of the machine in the local network (e.g. http://192.168.0.x) or the Docker host ip (e.g. http://172.17.0.1).

**Comment by laurentandrian** [comment]
so I looked who is lsitening to port 80:
[root@manager Mist-IO]# netstat -ltnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      5487/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      6050/master
tcp6       0      0 :::9096                 :::*                    LISTEN      26713/docker-proxy
tcp6       0      0 :::8040                 :::*                    LISTEN      25351/docker-proxy
tcp6       0      0 :::9097                 :::*                    LISTEN      26664/docker-proxy
tcp6       0      0 :::8041                 :::*                    LISTEN      25304/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      27979/docker-proxy
tcp6       0      0 :::8083                 :::*                    LISTEN      25477/docker-proxy
tcp6       0      0 :::8086                 :::*                    LISTEN      25425/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      5487/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      6050/master

it looks correct.

I do a wget using the IP address of the host: 
[root@manager Mist-IO]# wget http://10.122.42.222
--2019-03-01 12:44:00--  http://10.122.42.222/
Connecting to 10.122.42.222:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1557 (1.5K) [text/html]
Saving to: ‘index.html.2’

100%[========================================================================================================================================================>] 1,557       --.-K/s   in 0s

2019-03-01 12:44:00 (127 MB/s) - ‘index.html.2’ saved [1557/1557]

[root@manager Mist-IO]# more index.html.2
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<script type="text/javascript">
function getCookie(c_name) { // Local function for getting a cookie value
    if (document.cookie.length > 0) {
        c_start = document.cookie.indexOf(c_name + "=");
        if (c_start!=-1) {
        c_start=c_start + c_name.length + 1;
        c_end=document.cookie.indexOf(";", c_start);

        if (c_end==-1)
            c_end = document.cookie.length;

        return unescape(document.cookie.substring(c_start,c_end));
        }
    }
    return "";
}
function setCookie(c_name, value, expiredays) { // Local function for setting a value of a cookie
    var exdate = new Date();
    exdate.setDate(exdate.getDate()+expiredays);
    document.cookie = c_name + "=" + escape(value) + ((expiredays==null) ? "" : ";expires=" + exdate.toGMTString()) + ";path=/";
}
function getHostUri() {
    var loc = document.location;
    return loc.toString();
}
setCookie('YPF8827340282Jdskjhfiw_928937459182JAX666', '64.102.255.40', 10);
try {
    location.reload(true);
} catch (err1) {
    try {
        location.reload();
    } catch (err2) {
    	location.href = getHostUri();
    }
}
</script>
</head>
<body>
<noscript>This site requires JavaScript and Cookies to be enabled. Please change your browser settings or upgrade your browser.</noscript>
</body>
</html>


I did the same with docker host.

Same result, same html file

**Comment by d-mo** [comment]
That's very weird. Still, this doesn't seem to be a response by Mist's nginx. Perhaps the proxy that you mentioned or some piece of malware attempts to hijack the session? A quick Google search for some comments within that code give quite a few results that indicate something along those lines but I couldn't find a definitive answer: https://www.google.com/search?q="Local+function+for+getting+a+cookie+value"

One thing to try out is tailing the nginx & api logs `docker-compose logs --tail 0 -f api nginx` and check if your requests produce log entries in both containers.

**Comment by laurentandrian** [comment]
Hello,

I removed all the proxy configuration in docker and in Linux and I rebooted the machine.
Restarted docker and docker-compose.

When I do a local curl:
[root@manager Mist-CE]# curl -v http://10.122.42.222
* About to connect() to 10.122.42.222 port 80 (#0)
*   Trying 10.122.42.222...
* Connected to 10.122.42.222 (10.122.42.222) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.122.42.222
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.15.8
< Date: Mon, 04 Mar 2019 08:24:02 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 1557
< Connection: keep-alive
< Set-Cookie: session.id=d1b2738dc3bb95aa2b441125fee55ef33ecc9a7321f9df535a54e307cf2812e7; Path=/;
< Strict-Transport-Security: max-age=31536000
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block


I can see the response comes from nginx…


Here is the log from api and nginx while trying to access the web page with a browser.




[root@manager Mist-CE]# docker-compose logs --tail 0 -f api nginx
Attaching to mist-ce_nginx_1, mist-ce_api_1
api_1                   | [pid: 58|app: 0|req: 25/260] 172.23.0.19 () {40 vars in 822 bytes} [Mon Mar  4 08:25:21 2019] GET / => generated 1557 bytes in 203 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
nginx_1                 | 10.55.119.195 - - [04/Mar/2019:08:25:21 +0000] "GET / HTTP/1.1" 200 797 "http://10.122.42.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36" "-"
api_1                   | [pid: 54|app: 0|req: 24/261] 172.23.0.19 () {40 vars in 822 bytes} [Mon Mar  4 08:25:21 2019] GET / => generated 1557 bytes in 202 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
nginx_1                 | 10.55.119.195 - - [04/Mar/2019:08:25:21 +0000] "GET / HTTP/1.1" 200 797 "http://10.122.42.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36" "-"
api_1                   | [pid: 58|app: 0|req: 26/262] 172.23.0.19 () {40 vars in 822 bytes} [Mon Mar  4 08:25:21 2019] GET / => generated 1557 bytes in 203 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
nginx_1                 | 10.55.119.195 - - [04/Mar/2019:08:25:22 +0000] "GET / HTTP/1.1" 200 797 "http://10.122.42.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36" "-"
api_1                   | [pid: 57|app: 0|req: 53/263] 172.23.0.19 () {40 vars in 822 bytes} [Mon Mar  4 08:25:22 2019] GET / => generated 1557 bytes in 214 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
nginx_1                 | 10.55.119.195 - - [04/Mar/2019:08:25:22 +0000] "GET / HTTP/1.1" 200 797 "http://10.122.42.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36" "-"
api_1                   | [pid: 54|app: 0|req: 25/264] 172.23.0.19 () {40 vars in 822 bytes} [Mon Mar  4 08:25:22 2019] GET / => generated 1557 bytes in 204 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
nginx_1                 | 10.55.119.195 - - [04/Mar/2019:08:25:23 +0000] "GET / HTTP/1.1" 200 797 "http://10.122.42.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36" "-"
api_1                   | [pid: 66|app: 0|req: 54/265] 172.23.0.19 () {40 vars in 822 bytes} [Mon Mar  4 08:25:23 2019] GET / => generated 1557 bytes in 208 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
nginx_1                 | 10.55.119.195 - - [04/Mar/2019:08:25:23 +0000] "GET / HTTP/1.1" 200 797 "http://10.122.42.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36" "-"
api_1                   | [pid: 56|app: 0|req: 20/266] 172.23.0.19 () {40 vars in 822 bytes} [Mon Mar  4 08:25:23 2019] GET / => generated 15


So looks to me the nginx is receiving the requests.


Laurent

**Comment by d-mo** [comment]
Can you try with v4.1.1?
