### ISSUE TITLE
Text contrast issue on "No clouds found." message

### ISSUE THREAD

**Issue by marclaporte** [mistio/mist-ce#953]
![2019-04-07-Mist-text-contrast-issue](https://user-images.githubusercontent.com/1004261/55685234-acd5db00-5921-11e9-9ee9-fc1703423d44.png)

This is very low priority, but I am adding as Good First Issue :-)

**Comment by marclaporte** [comment]
https://mist.io/networks also has a contrast issue, but all the others (Machines, Volumes, etc.) are good.

**Comment by xristina** [comment]
@marclaporte thank you for reporting this. We'll soon have a fix for the next release.

**Comment by d-mo** [comment]
Fixed on v4.1.0
