### ISSUE TITLE
IBM Cloud Access

### ISSUE THREAD

**Issue by hwinkel** [mistio/mist-ce#955]
I cannot find the API Token within the soflayer Portal. Is this still available or do you support the IBM Portal as well?

**Comment by d-mo** [comment]
It's still available, at least in our account, near the bottom of the user profile page, under the section "API Access Information": https://control.softlayer.com/account/user/profile

Please let me know if that's not the case for you.

**Comment by hwinkel** [comment]
I found it my self in the IBM Cloud under: Management, Access (IAM), IBM Cloud API Keys, Classic Infrastructure API Key.

**Comment by d-mo** [comment]
Great! Thanks for sharing.
