### ISSUE TITLE
KVM VMs IP/hostname info does not exist and user is not able to fill it up

### ISSUE THREAD

**Issue by ldanicel** [mistio/mist-ce#962]
Doing a test run for mist.io community edition:
1) Add KVM host via ssh key - VMs show up in the Machines tab
2) Trying to enable monitoring on them - I get notified I don't have a key associated.
I add the key.
I get an error - hostname does not exist
After this event I am able to enable monitoring as for some reason mist thinks I've solved my key association issues but the agent deployment hangs indefinitely.

What is the correct dependency list or approach to this workflow ?
I tried installing kvm guest tools inside the vm but as far as I've seen hostname/IPs for the VM is not filled in mist.

**Comment by d-mo** [comment]
Sounds like your VM was not getting an IP addressable by Mist. If Mist can connect with SSH then enabling monitoring should work.

In any case, [v4.3.0](https://github.com/mistio/mist-ce/releases/tag/) includes many improvements regarding KVM support. You may want to try it again.
