### ISSUE TITLE
Issue KVM: Make sure ssh key and username are valid

### ISSUE THREAD

**Issue by wiwa1978** [mistio/mist-ce#963]
I have a server running Ubuntu 18.04 and configured it to run KVM. I can successfully work viq Virtal Machine Manager to create virtual machines. I installed mist.io v4.1.4 to have a nicer webinterface.

Via the webinterface I would like to connect to my KVM setup. The host Ubuntu server is having IP: 192.168.10.10 and I configured a user 'wim' which has sudo rights. On that host, also docker is running (on a seperate bridge) and all docker containers are up (via docker-compose up -d). 

On my host, I created an SSH key (without passphrase) under the user (wim) .ssh folder using the following command: 
`ssh-keygen -m PEM -t rsa -b 4096`

Then, using the mist.io user interface, I'm adding this SSH key via the 'upload' method (not copy/paste).

Doing this always getting the following error message:
> Cloud unavailable: Make sure ssh key and username are valid

![Screenshot from 2019-10-09 14-01-51](https://user-images.githubusercontent.com/4012455/66479758-6cf0db80-ea9d-11e9-8dff-3c1aa975ca28.png)

**The issue:**

```
api_1                   | 2019-10-09 13:33:17,398 INFO  [mist.api.clouds.methods][uWSGIWorker4Core0] Adding new cloud in provider 'libvirt'
api_1                   | 2019-10-09 13:33:17,400 WARNI [mist.api.helpers][uWSGIWorker4Core0] Got param 'machine_hostname' when expecting 'host', transforming.
api_1                   | 2019-10-09 13:33:17,400 WARNI [mist.api.helpers][uWSGIWorker4Core0] Got param 'machine_user' when expecting 'username', transforming.
api_1                   | 2019-10-09 13:33:17,400 WARNI [mist.api.helpers][uWSGIWorker4Core0] Got param 'machine_key' when expecting 'key', transforming.
api_1                   | 2019-10-09 13:33:17,400 WARNI [mist.api.helpers][uWSGIWorker4Core0] Got param 'ssh_port' when expecting 'port', transforming.
api_1                   | libvirt: XML-RPC error : Cannot recv data: wim@192.168.10.10: Permission denied (publickey,password).: Connection reset by peer
api_1                   | 2019-10-09 13:33:18,023 ERROR [mist.api.clouds.controllers.base][uWSGIWorker4Core0] Error while connecting to <class 'mist.api.clouds.models.LibvirtCloud'> cloud KVM (libvirt) (e3ce92199481448e989b423457fe4023) of Org wauterw@gmail.com (1 teams - 1 members)
api_1                   | Traceback (most recent call last):
api_1                   |   File "/mist.api/libcloud/libcloud/compute/drivers/libvirt_driver.py", line 158, in __init__
api_1                   |     self.connection = libvirt.open(uri)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/libvirt.py", line 277, in open
api_1                   |     if ret is None:raise libvirtError('virConnectOpen() failed')
api_1                   | libvirt.libvirtError: Cannot recv data: wim@192.168.10.10: Permission denied (publickey,password).: Connection reset by peer
api_1                   | 
api_1                   | During handling of the above exception, another exception occurred:
api_1                   | 
api_1                   | Traceback (most recent call last):
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/base.py", line 92, in connect
api_1                   |     return self._connect()
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/compute/controllers.py", line 1492, in _connect
api_1                   |     ssh_port=int(port))
api_1                   |   File "/mist.api/libcloud/libcloud/compute/drivers/libvirt_driver.py", line 166, in __init__
api_1                   |     raise Exception("Make sure ssh key and username are valid")
api_1                   | Exception: Make sure ssh key and username are valid
api_1                   | 2019-10-09 13:33:18,026 ERROR [mist.api.clouds.controllers.main.base][uWSGIWorker4Core0] Will not update cloud <class 'mist.api.clouds.models.LibvirtCloud'> cloud KVM (libvirt) (e3ce92199481448e989b423457fe4023) of Org wauterw@gmail.com (1 teams - 1 members) because we couldn't connect: CloudUnavailableError('Cloud unavailable: Make sure ssh key and username are valid')
```

In terms of troubleshooting I did the following:

**1) Connect via ssh via mist.api**

```
wim@server:~/Documents/mistio$ docker-compose exec api sh
/mist.api # ssh -vvv -i /home/wim/.ssh/id_rsa wim@192.168.10.10
```
Warning: Identity file /home/wim/.ssh/id_rsa not accessible: No such file or directory.

Outcome: I can connect to the server but it's asking still my password. Guess this is becqause it does not find the ssh key. The ssh key is installed on the server, not in the docker mist.api container. That's the reason it displays the warning I assume. Still I can connect to the server via password then.

**2) Adding the KVM host via 'Other server'**

This works, see screenshot for the settings I used.
![Screenshot from 2019-10-09 14-19-24](https://user-images.githubusercontent.com/4012455/66480889-e1c51500-ea9f-11e9-82e5-84aca841e273.png)
While the server gets added to the interface, the amount of machines remains 0 however there is certainly 1 virtual machine running on top of KVM.

**3)Changing keys**
My SSH key starts with ----BEGIN RSA PRIVATE KEY------ and not -----BEGIN OPENSSH PRIVATE KEY-----

All in all, this issue seems to be very similar to the issue #954 but in my case the suggested solution does not work. I'm already using the old format key and uploading the key (not copy/pasting to avoid the newline issue decribed in issue #954.

Should I copy the rsa key to the mist API container?

**Comment by d-mo** [comment]
This has been fixed in Mist v4.2.0. Please re-open if that's not the case.
