### ISSUE TITLE
Emails are sent from "Mist.io team <we@mist.io>", which breaks Postmark SMTP

### ISSUE THREAD

**Issue by jamesponddotco** [mistio/mist-ce#965]
Hi,

Is there any way to change the default "From" address on emails? We use Postmark as our SMTP provider, and since all emails come from **Mist.io team <we@mist.io>** instead of the our own domain, Postmark does not accept the emails, which means they are not sent.

My **settings.py** file seems to be configured correctly and Postmark does receive the email, it just doesn't send it because of the from field.

**Error from Postmark:**

`ErrorCode: '400', Message: 'The 'From' address you supplied ("Mist.io team" <we@mist.io>) is not a Sender Signature on your account. Please add and confirm this address in order to be able to use it in the 'From' field of your messages.'.`

**The settings.py file:**

```
MAILER_SETTINGS = {
    'mail.host': "smtp.postmarkapp.com",
    'mail.port': "25",
    'mail.tls': True,
    'mail.starttls': True,
    'mail.username': "",
    'mail.password': "",
}
```

A

**Comment by d-mo** [comment]
You can override the default value of EMAIL_FROM with the address of your choice. All configuration variables defined in https://github.com/mistio/mist.api/blob/master/src/mist/api/config.py can be overridden in your settings/settings.py

**Comment by jamesponddotco** [comment]
Ah, I missed that. Thanks, @d-mo!
