### ISSUE TITLE
MKTEMP issue

### ISSUE THREAD

**Issue by ybelot** [mistio/mist-ce#966]
Hello,

i am unable to launch MIST.
Some of the containers seem to exit due to this : (log for API)
api_1                   | + dirname /etc/mist/settings/settings.py
api_1                   | + conf_dir=/etc/mist/settings
api_1                   | + mkdir -p /etc/mist/settings
api_1                   | + mktemp -p /etc/mist/settings
api_1                   | mktemp: Permission denied
api_1                   | + tmp_file=

can someone help me ? please
yann

**Comment by d-mo** [comment]
What OS are you installing it on? If SELinux is enabled try disabling it.

Also, try resetting the ownership of all installation files, just in case something got mixed up e.g. `sudo chown -R ybelot .`

**Comment by ybelot** [comment]
hello,
thanks for your reply, i am using centos7.

**Comment by ybelot** [comment]
just tried using temp disabling of SELINUX , and it works ... :)
thanks a lot
best regards 
yann
