### ISSUE TITLE
Adding vSphere 6.7 cloud only imports only networks and nothing else. 

### ISSUE THREAD

**Issue by ewjannece** [mistio/mist-ce#967]
When I add vsphere 6.7 into mist, I only networks show up. Tried /folders/ and the username and password was correct. Maybe because my ssl cert is self generated? I'm including the log. Let me know if there anything else I can add to help. 

`{
"log_id": "f0637a83005e44ed953d849bcabf84d6",
"owner_id": "a30f2fbe6caf4cbd92a56b530ee91e15",
"session_id": "5df23222fc886e0077f6b815",
"type": "request",
"error": false,
"tags": [
 "logs",
 "request"
],
"@timestamp": "2019-12-13T09:31:07.799Z",
"user_id": "fcd73070c143412099fa1cc407877d25",
"@version": "1",
"action": "add_cloud",
"time": 1576229467.7998567,
"cloud_id": "7623237fd1214d05999c0a290755f740",
"email": "[REDACTED]",
"request_path": "/api/v1/clouds",
"request_method": "POST",
"request_ip": "192.168.0.10",
"user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0",
"response_code": 200,
"request_params": {
"provider": "vsphere",
"title": "VMware vSphere",
"host": "vcenter.is.virtual",
"username": "administrator@vsphere.local",
"password": "***CENSORED***"
},
"response_body": "{"id": "7623237fd1214d05999c0a290755f740", "title": "VMware vSphere", "provider": "vsphere", "enabled": true, "dns_enabled": false, "observation_logs_enabled": true, "state": "online", "polling_interval": 1800, "tags": {}, "owned_by": "fcd73070c143412099fa1cc407877d25", "created_by": "fcd73070c143412099fa1cc407877d25", "host": "vcenter.is.virtual", "username": "administrator@vsphere.local", "max_properties_per_request": 20, "index": 0}"
}`

**Comment by ewjannece** [comment]
> fake@fakeemails.com

ts

**Comment by d-mo** [comment]
Hi @ewjannece,
you could try the following:
1. Tail the api log using `docker-compose logs -f --tail 10 api`
2. Invoke the list-machines API endpoint with an HTTP GET request to /api/v1/clouds/7623237fd1214d05999c0a290755f740/machines (on a new browser tab while logged in)
3. Check for errors & tracebacks in the log and send them over.

Thanks!

**Comment by d-mo** [comment]
@ewjannece Looks like there was a bug in Mist v4.2.0 that affected vSphere. It has been fixed in v4.2.1. Maybe that was the issue you encountered?

https://github.com/mistio/mist-ce/releases/tag/v4.2.1

If the problem persists with v4.2.1, please send us over the relevant logs as described above.

**Comment by ewjannece** [comment]
4.2.1 made it worse. Now it can't get past the self-signed cert. 
I didn't change anything on the VMware vSphere cluster. Let me know if there is anything I can do to help. 

`api_1                   | 2019-12-18 00:48:22,917 ERROR [mist.api.clouds.controllers.main.base][uWSGIWorker7Core0] Will not update cloud <class 'mist.api.clouds.models.VSphereCloud'> cloud VMware vSphere (ab05079704ac4f8e84ec622c168c0e17) of Org gene.org (1 teams - 1 members) because we couldn't connect: CloudUnavailableError('Cloud unavailable: Remote end closed connection without response')
api_1                   | 2019-12-18 00:48:22,929 INFO  [mist.api.views][uWSGIWorker7Core0] MistError: CloudUnavailableError('Cloud unavailable: Remote end closed connection without response')
api_1                   | [pid: 108|app: 0|req: 2/21] 172.18.0.27 () {44 vars in 840 bytes} [Wed Dec 18 00:47:34 2019] POST /api/v1/clouds => generated 64 bytes in 48239 msecs (HTTP/1.0 503) 2 headers in 96 bytes (1 switches on core 0)
api_1                   | 2019-12-18 00:50:49,509 INFO  [mist.api.clouds.methods][uWSGIWorker7Core0] Adding new cloud in provider 'vsphere'
api_1                   | 2019-12-18 00:51:37,914 ERROR [mist.api.clouds.controllers.base][uWSGIWorker7Core0] Error while connecting to <class 'mist.api.clouds.models.VSphereCloud'> cloud VMware vSphere (ab10e90214774347a1c6816c7841f71d) of Org gene.org (1 teams - 1 members)
api_1                   | Traceback (most recent call last):
api_1                   |   File "/mist.api/libcloud/libcloud/compute/drivers/vsphere.py", line 84, in __init__
api_1                   |     host=host, port=port, user=username, pwd=password
api_1                   |   File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 836, in SmartConnect
api_1                   |     sslContext)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
api_1                   |     sslContext)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
api_1                   |     path + "/vimServiceVersions.xml", sslContext)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 604, in __GetElementTree
api_1                   |     conn.request("GET", path)
api_1                   |   File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
api_1                   |     self._send_request(method, url, body, headers, encode_chunked)
api_1                   |   File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
api_1                   |     self.endheaders(body, encode_chunked=encode_chunked)
api_1                   |   File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
api_1                   |     self._send_output(message_body, encode_chunked=encode_chunked)
api_1                   |   File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
api_1                   |     self.send(msg)
api_1                   |   File "/usr/local/lib/python3.7/http/client.py", line 966, in send
api_1                   |     self.connect()
api_1                   |   File "/usr/local/lib/python3.7/http/client.py", line 1422, in connect
api_1                   |     server_hostname=server_hostname)
api_1                   |   File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
api_1                   |     session=session
api_1                   |   File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
api_1                   |     self.do_handshake()
api_1                   |   File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
api_1                   |     self._sslobj.do_handshake()
api_1                   | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)`

**Comment by ewjannece** [comment]
Works now. Thanks!
