### ISSUE TITLE
Safari login not possible

### ISSUE THREAD

**Issue by LukasK13** [mistio/mist-ce#968]
When trying to login from the landing page by clicking on _sign in_, a empty page is displayed.
The JavaScript console shows the following error: `TypeError: this.element.animate is not a function. (In 'this.element.animate([{transform:"scale(0)"},{transform:"scale(1)"}],{duration:duration,easing:"cubic-bezier(0.3, 0.2, 1.0, 0.2)",fill:"forwards"})', 'this.element.animate' is undefined)`.
A quick Google search shows, that the library [web-animations-js](https://github.com/web-animations/web-animations-js) is necessary for animations in safari.
Adding `<script src="https://rawgit.com/web-animations/web-animations-js/master/web-animations.min.js"></script>` to _index.html_ in the container _landing_ fixes the problem.

**Comment by d-mo** [comment]
Thanks @LukasK13 for reporting this. I can confirm the issue. We'll have it fixed in the next release.

**Comment by lacf95** [comment]
Also occurring on **iPad OS 13.3.1** Safari if anyone is wondering why it does not work

**Comment by d-mo** [comment]
Fixed in [v4.3.0](https://github.com/mistio/mist-ce/releases/tag/)
