### ISSUE TITLE
Using the Helm Chart

### ISSUE THREAD

**Issue by VirtuallyLG** [mistio/mist-ce#969]
Looking for a step by step guide on using the Helm chart, didnt see any information if I need to add a helm repo or just some basic information on how to use the chart

**Comment by VirtuallyLG** [comment]
also when using lint to valdate
 helm lint .
==> Linting .
[ERROR] Chart.yaml: apiVersion is required. The value must be either "v1" or "v2"

also looks like rabbitmq is missing in the templates folder
found in Chart.yaml, but missing in charts/ directory: rabbitmq-ha

**Comment by d-mo** [comment]
Thanks for the reminder to document this!

Try the following after checking out the latest master or staging branch. Tested with Helm v2.16.1

```
HOSTNAME=mist.mydomain.com
RELEASE=mist-mydomain
helm init --client-only
helm repo update
helm dependency update ./chart/mist/
helm upgrade --install --namespace mist --set http.host="$HOSTNAME" $RELEASE ./chart/mist
```
To configure TLS add `--set http.tlsSecret=your-tls-secret`.

The chart assumes your cluster is running prometheus-operator in the monitoring namespace. If that's not the case you can override the respective flags in values.yaml.

Please let me know if that works for you.

**Comment by VirtuallyLG** [comment]
thanks for the info, im still getting errors with rabbitmq-ha, should there be a yaml for that in the templates folder?

[root@centos mist-ce]# helm upgrade --install --namespace mist --set http.host="$HOSTNAME" $RELEASE ./chart/mist
Release "mist-mydomain" does not exist. Installing it now.
Error: found in Chart.yaml, but missing in charts/ directory: rabbitmq-ha
[root@centos mist-ce]#

**Comment by d-mo** [comment]
No, there shouldn't be a yaml file for rabbitmq-ha. It's defined as a dependency in chart/mist/requirements.yaml and it being pulled when you run the command `helm dependency update ./chart/mist/` as noted above before installing the chart.

What's the output of that command in your case? What helm version are you using?

**Comment by VirtuallyLG** [comment]
I was using helm 3.0 so have downgraded to 2.16.1 I now get the following error

[root@centos mist-ce]# helm dependency update ./chart/mist/
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading rabbitmq-ha from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
[root@centos mist-ce]# helm upgrade --install --namespace mist --set http.host="$HOSTNAME" $RELEASE ./chart/mist
Error: could not find tiller

**Comment by VirtuallyLG** [comment]
OK so after fixing tiller and RBAC I'm getting API version errors I believe 
[root@centos mist-ce]# helm upgrade --install --namespace mist --set http.host="$HOSTNAME" $RELEASE ./chart/mist
Release "mist-mydomain" does not exist. Installing it now.
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]
[root@centos mist-ce]#


can you confirm the K8s supported version that Mist will run with, I'm running 1.16.4

**Comment by d-mo** [comment]
We're still on Kubernetes 1.15. A quick search reveals an API change in 1.16 which is probably the cause behind your issue.
https://stackoverflow.com/questions/58481850/no-matches-for-kind-deployment-in-version-extensions-v1beta1

Do you have an 1.15 cluster to try it out? In the meantime we'll look into updating our Helm chart for K8s 1.16.

**Comment by d-mo** [comment]
@VirtuallyLG I updated the Helm chart to work with Kubernetes 1.16
You try it out using the latest master. Please let me know if that works for you.

**Comment by VirtuallyLG** [comment]
Thanks for the update, managed to get some time this afternoon to dig a bit deeper, the Influxdb and elasticsearch was stuck in pending but after looking at the events the persistent storage was stuck as the min volume I can assign is 1Gb, so no problem after the change in the yaml for those pods. I am assuming as you are using HPA that a metric server is required, I used one just in case, I also deployed Prometheus and Grafana as I saw its also leveraged. 
I will be destroying and rebuilding again tomorrow to review the flow, one additional question I had was on the resources required for deployment. I am building on 4 worker nodes with 4 vCPUs and 6Gb ram per node, what's the min spec for a cluster that's required.

**Comment by d-mo** [comment]
Good to know about the min volume size. We'll increase the size of the initially allocated volume to 1Gb in order to prevent such issues.

The celery HPA can optionally leverage some custom metric provided by RabbitMQ through Prometheus for more optimal autoscaling. You're quite fine without it though.

Regarding the min specs, you have more than enough. I was able set it up on a (single node) minikube with 4vCPUs and 8Gb of ram total. That said, more ram would be even better for the databases (Elasticsearch, InfluxDB & MongoDB) and there would be more room for autoscaling if the load increases in some services.

Let me know how it goes tomorrow.

**Comment by VirtuallyLG** [comment]
the installation on a fresh 1.16 cluster went through without issues. I am now having problems logging into the portal, I exposed the UI via NodePort and had created an account in mist.io but when I log into the UI on the k8s cluster is says user unauthorized,  I also created an account via the link on the portal just in case that was creating a user locally on the cluster.

**Comment by VirtuallyLG** [comment]
Just to add that I didn't modify the values.YAML file so I guess I need to change values in there, may the SMTP settings, just need guidance on what needs to be modified as a minimum for a quick start

**Comment by d-mo** [comment]
Yes, SMTP settings need to configured in order to allow users to sign up normally. The values that need to be set are `smtp.host`, `smtp.port`, `smtp.user`, `smtp.password`. Also `smtp.tls` should be set to true if the SMTP server requires TLS.

By default Mist uses the internal mailmock service that prints all emails to the standard output instead of sending them. So, even if you don't configure an actual smtp server, you should be able to see your registration confirmation links by tailing the logs of the mailmock pod.

Alternatively, you can also add users programmatically by running the following command within an api pod: `/mist.api/bin/adduser your@email.com`.

Let me know if that helps.

**Comment by VirtuallyLG** [comment]
great, thanks, will use the API. thanks again for your help
