### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by m18646461005** [mistio/mist-ce#979]
log：

` 
Python main interpreter initialized at 0x562ddd76d1a0
api_1                   | uWSGI running as root, you can use --uid/--gid/--chroot options
api_1                   | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
api_1                   | python threads support enabled
api_1                   | your server socket listen backlog is limited to 100 connections
api_1                   | your mercy for graceful operations on workers is 60 seconds
api_1                   | mapped 4433847 bytes (4329 KB) for 32 cores
api_1                   | *** Operational MODE: preforking ***
api_1                   | Loading paste environment: config:/mist.api/uwsgi.ini
api_1                   | 2020-04-28 09:28:56,251 WARNI [mist.api.config][MainThread] MIST_API_DIR is /mist.api
api_1                   | Traceback (most recent call last):
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
api_1                   |     return loadobj(APP, uri, name=name, **kw)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 277, in loadobj
api_1                   |     global_conf=global_conf)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
api_1                   |     global_conf=global_conf)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 326, in _loadconfig
api_1                   |     return loader.get_context(object_type, name, global_conf)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 459, in get_context
api_1                   |     section)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 481, in _context_from_use
api_1                   |     object_type, name=use, global_conf=global_conf)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 412, in get_context
api_1                   |     global_conf=global_conf)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
api_1                   |     global_conf=global_conf)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 334, in _loadegg
api_1                   |     return loader.get_context(object_type, name, global_conf)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 625, in get_context
api_1                   |     object_type, name=name)
api_1                   |   File "/usr/local/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 651, in find_egg_entry_point
api_1                   |     possible.append((entry.load(), protocol, entry.name))
api_1                   |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2444, in load
api_1                   |     return self.resolve()
api_1                   |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in resolve
api_1                   |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
api_1                   |   File "/mist.api/src/mist/api/__init__.py", line 13, in <module>
api_1                   |     from mist.api import config
api_1                   |   File "/mist.api/src/mist/api/config.py", line 1368, in <module>
api_1                   |     'provider': Provider.KUBEVIRT,
api_1                   | AttributeError: type object 'Provider' has no attribute 'KUBEVIRT'`

**Comment by d-mo** [comment]
Are you using the latest release? Looks like you're on a dev setup and your libcloud is not up to date.
