### ISSUE TITLE
update './settings/settings.py ' the 'JS_BUILD = False'  after server 502

### ISSUE THREAD

**Issue by m18646461005** [mistio/mist-ce#980]
Can you answer the following in detail
thank you
`When doing front-end development, it's usually more convenient to serve the source code instead of the bundles. To do that, edit settings/settings.py and set JS_BUILD = False. Restart the api container for the changes to take effect`

After trying this setup ，implement `./restart.sh api` ，server 502
set './settings/settings.py    JS_BUILD = False'  Comment out  Server is running normally
I tried to change the code in setting.py. After restarting the API, the server will 502

**Comment by d-mo** [comment]
Check the status and the logs of the api container. There's probably a syntax error in settings.py which could be causing the container to restart a few times in a row before failing.
