### ISSUE TITLE
Dashboard no data

### ISSUE THREAD

**Issue by m18646461005** [mistio/mist-ce#983]
Why dashboard no data

**Comment by d-mo** [comment]
Many possible reasons. Perhaps CORE_URI is not configured correctly in settings.py, the agent was not installed successfully, the monitored machine cannot access to CORE_URI, InfluxDB could be overloaded, etc.

If you'd like to report an issue please open more specific tickets and do you own research first. For example look for hints in the logs. You can see the telegraf log on the target machine with something link `journalctl -f -u mist-telegraf`

**Comment by m18646461005** [comment]
telegraf log：
```
May 29 09:53:16 iZm5ebxldyuzahr52ebxwiZ telegraf[24324]: 2020-05-29T01:53:16Z E! [outputs.influxdb]: when writing to [http://192.168.100.178/ingress/dab4af647c8b3dbe01349ab7ec80161840b4030d8b684f5b55da81837df899c8]: Post http://192.168.100.178/ingress/dab4af647c8b3dbe01349ab7ec80161840b4030d8b684f5b55da81837df899c8/write?consistency=any&db=telegraf: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
May 29 09:53:16 iZm5ebxldyuzahr52ebxwiZ telegraf[24324]: 2020-05-29T01:53:16Z E! Error writing to output [influxdb]: could not write any address
```
How to solve this situation
