### ISSUE TITLE
Linode configuration does not work

### ISSUE THREAD

**Issue by abhas** [mistio/mist-ce#988]
The steps documented on: https://docs.mist.io/article/25-adding-linode for adding a Linode API key don't work. I think that Linode support was for their earlier management interface. And the current management interface has a different API. So its not possible to add or use Linode with Mist-CE at the moment.

**Comment by abhas** [comment]
![image](https://user-images.githubusercontent.com/255701/86580699-b0309a00-bf9c-11ea-86c3-c8964abee9f3.png)

This is a screenshot of the error.

**Comment by d-mo** [comment]
Thank you @abhas for the heads up.

It looks like Linode updated their API recently. The old API still works if you have a v3 token, but you can only create tokens for the new v4 API from the Linode portal.

We're looking into this. It will most likely be addressed in Mist v4.4

**Comment by cpsaltis** [comment]
Linode API v4 is supported for some time now @abhas. Sorry, for missing this ticket. You can also quickly spin up Mist from Linode's Marketplace. See https://www.linode.com/marketplace/apps/mist/mist-cloud-management-platform/
