### ISSUE TITLE
 LXD cloud machine SHELL do not work

### ISSUE THREAD

**Issue by diegomontoya** [mistio/mist-ce#992]
Version: Latest mistio-ce

Topology

Server A: lxd host with lxdbr0 on 10.0.1.1/24 network
Server B: lxd host with lxdbr0 on 10.0.1.1/24 network

Server A and B can talk via WAN

1) Mistio-ce is installed in a LXD container on Server A
2) Server B WAN IP is added to Mistio-ce admin UI via "Add Cloud -> LXD"
3) Click on any Server B lxd machine in Mistio-ce and attempt to access SHELL will fail.  Stuck on "Connecting to 10.0.1.xxx..."

Mistio-ce can control the Server B lxd machines fine. Starting/stopping a lxd machine works. Only SHELL does not work.

**Comment by Eis-D-Z** [comment]
In this setting, at the moment you can ssh from mist to the server B machine since it is reachable, the machines on server B will need a reachable IP and to run an ssh daemon in order to ssh into them.

**Comment by diegomontoya** [comment]
Currently mistio only support ssh shell to LXD containers so there are two issues at play here 1) the container has local ip 2) there is no sshd in the container. Hopefully mist can support the LXD api for a ssh-less shell.
