### ISSUE TITLE
Any plans to update ui library?

### ISSUE THREAD

**Issue by segrey11** [mistio/mist-ce#999]
Hi.

Currently the UI is built with Polymer v2.
Are there any plans to update current or migrate to another UI library?
Getting rid of bower would be the great thing as well.

Thanks in advance.

**Comment by d-mo** [comment]
Hi @segrey11 ,

Perfect timing! We just finished upgrading to Polymer 3 / Web Components v1 and bower is gone forever. It will be part of the upcoming v4.4 release. You can try it out by fetching the latest staging branch and updating the assorted submodules. It got merged a few hours ago.

Along the way, we might rewrite some components using [lit-element](https://lit-element.polymer-project.org/) and we'll probably start using [Redux](https://redux.js.org/) for managing state. That said, we're not planning to migrate every existing component. Now that we support Web Components v1 it should be trivial to mix and match.

**Comment by segrey11** [comment]
Great news! Thanks a lot.
